:PROPERTIES:
:ID:       1ff88c66-b17d-40b3-aefe-70a96aa13831
:ROAM_ALIASES: "\"Peak\""
:END:
#+setupfile: ../../hugo_setup.org
#+title: Peak: Secrets from the New Science of Expertise
#+Author: Anders Ericsson and Robert Pool
#+Date: <2019-08-22 Thu>


/Note: These notes are not complete as I have just started univerity and they are not a priority./

*[[id:a2857bde-9233-4ed3-97b1-8f0cc4bd6b44][Mental Representations]]*:

Learning is about creating mental representations—mental modals that can be used to make sense of complex information which would seem quasi-random to a layperson. For example, a professional pianist is able to look a sheet of music and without ever having heard it, know what it will sound like. These mental representations exist as neural structures inside your brain which are solidified and developed through practice.

The purpose of deliberate practice is to increase the quality of these mental representations.

# TODO Expand on the faults of typical practice
*The usual approach:*

Repetition alone will not make you better. You will not become a better skier, a better piano player or a better student. The type of naive practice that we typically fall into—doing something repeatedly, and expecting that the repetition alone will improve your performance—is just that, naive.

*Purposeful practice:*

Purposeful practice is a more thoughtful approach to improvement. It:

1. *Has well-defined, specific goals.* For example, /play section B of the solo at 120bpm with no  mistakes./ Without a goal, success cannot be measured.
2. *Is focused.* The practice must occupy your full attention. This means no distractions and following the plan.
3. *Involves feedback.* You need to be able to reliably tell whether or not you executed correctly. For example, playing section B of the solo perfectly may mean /no wrong notes/ or /with all indicated dynamics/.
4. *Gets you out of your comfort zone.* Practice is not necessarily fun. It is type 2. You will not improve without stretching yourself.

While powerful, purposeful practice has its limitations. It is possible, while practicing purposefully, to practice something the /wrong way/ and therefore create bad habits which may need to be corrected in the future. This is where deliberate practice comes in.

*Deliberate practice:*

Deliberate practice expands of the principles of purposeful practice by adding the following 2 rules. Deliberate practice:

1. *Develops skills that have been mastered by experts and for which effective training techniques have already been developed.* This way, you can be assured that you are creating effective mental representations.
2. *Employs teachers to guide a student's practice and to give effective feedback.* Teachers can ensure that you have a solid foundation of fundamental skills before advancing to ensure expert performance. Furthermore, they can provide professional feedback to identify weaknesses and develop a plan for improving them.
