:PROPERTIES:
:ID:       b303f17b-ea06-44f5-bd9a-85172c7b7c7d
:END:
#+setupfile: ../../hugo_setup.org
#+title: Permanent Record

- author :: [[id:33e611d4-169a-4dd9-a441-e18fe284ba9b][Edward Snowden]]
- tags :: 


* The Book in 3 Sentences

This is the autobiography of Edward Snowden, the CIA and later NSA technologist who revealed the extent of the nation's mass surveillance program to the world. While it is well known that he leaked a huge archive of classified documents to the press, the extend to which the government was spying on its citizens and the repercussions of his actions are not as well understood.

* Impressions

I have always been concerned about privacy. To me, it seems like a hidden threat that is not well enough understood by the average person. Yet whenever I am asked to defend [[id:20a8b435-ae34-45cc-9dab-84aab85d91aa][The importance of privacy]] and the dangers of mass surveillance to others, I struggle to find the right words. Snowden is both an eloquent writer and speaker, and his book is the best argument we have for the importance of privacy. The being said, I wish the book included a few pages describing exactly the problem we're facing, how it affects everyday people, and what we need to do to fix it.

* How the Book Changed Me

This book didn't change me too profoundly, as through my own research and experience I've come to learn about many of the dangers he speaks of, yet it did convince me all the more of the importance of fighting for our right to privacy.

* Top 3 Highlights

#+begin_quote
In the 1990s, the Internet had yet to fall victim to the greatest iniquity in digital history: the move by both government and businesses to link, as intimately as possible, users’ online personas to their offline legal identity.

— [[id:33e611d4-169a-4dd9-a441-e18fe284ba9b][Edward Snowden]]
#+end_quote


#+begin_quote
 Distance favors intimacy: no one talks more openly than when they’re alone in a room, chatting with an unseen someone alone in a different room. Meet that person, however, and you lose your latitude. Your talk becomes safer and tamer, a common conversation on neutral ground.

— [[id:33e611d4-169a-4dd9-a441-e18fe284ba9b][Edward Snowden]]
#+end_quote


#+begin_quote
Saying that you don’t need or want privacy because you have nothing to hide is to assume that no one should have, or could have, to hide anything—including their immigration status, unemployment history, financial history, and health records.
— [[id:33e611d4-169a-4dd9-a441-e18fe284ba9b][Edward Snowden]]
#+end_quote


* Highlights

- After that, companies realized that people who went online were far less interested in spending than in sharing, and that the human connection the Internet made possible could be monetized.

- In the 1990s, the Internet had yet to fall victim to the greatest iniquity in digital history: the move by both government and businesses to link, as intimately as possible, users’ online personas to their offline legal identity.

- The early Internet’s dissociative opportunities actually encouraged me and those of my generation to change our most deeply held opinions, instead of just digging in and defending them when challenged. This ability to reinvent ourselves meant that we never had to close our minds by picking sides, or close ranks out of fear of doing irreparable harm to our reputations.

- I started hacking—which remains the sanest, healthiest, and most educational way I know for kids to assert autonomy and address adults on equal terms.

- To hack a system requires getting to know its rules better than the people who created it or are running it, and exploiting all the vulnerable distance between how those people had intended the system to work and how it actually works,

- It’s this egalitarian nature of hacking—which doesn’t care who you are, just how you reason—that makes it such a reliable method of dealing with the type of authority figures so convinced of their system’s righteousness that it never occurred to them to test it.

- Dunbar’s number, the famous estimate of how many relationships you can meaningfully maintain in life, is just 150.

- 9/11 left holes. Holes in families, holes in communities. Holes in the ground. Now, consider this: over one million people have been killed in the course of America’s response.

- I didn’t want to live in a world where everyone had to pretend that they were perfect, because that was a world that had no place for me or my friends.

- In my experience, the more you’ve communicated with someone online, the more disappointed you’ll be by meeting them in person.

- Things that are the easiest to say on-screen become the most difficult to say face-to-face.

- Distance favors intimacy: no one talks more openly than when they’re alone in a room, chatting with an unseen someone alone in a different room. Meet that person, however, and you lose your latitude. Your talk becomes safer and tamer, a common conversation on neutral ground.

- My mind was a mash-up of the values I was raised with and the ideals I encountered online.

- Here was this wild, open new frontier that belonged to anyone bold enough to settle it, swiftly becoming colonized by governments and corporate interests that were seeking to regulate it for power and profit.

- These sensationalist cases can lead the public to believe that the government employs contractors in order to maintain cover and deniability, off-loading the illegal or quasi-legal dirty work to keep its hands clean and conscience clear. But that’s not entirely true, or at least not entirely true in the IC, which tends to focus less on deniability and more on never getting caught in the first place.

- Nothing inspires arrogance like a lifetime spent controlling machines that are incapable of criticism.

- The worst-kept secret in modern diplomacy is that the primary function of an embassy nowadays is to serve as a platform for espionage.

- Van Eck phreaking.

- Peering at life through a window can ultimately abstract us from our actions and limit any meaningful confrontation with their consequences.

- in my experience most people will jump at the chance to explain exactly how much more they know than you do about something they care about deeply.

- in Switzerland fines aren’t flat sums but based on a percentage of income, and his driver’s license was suspended for three months—

- the NSA could collect whatever communications records it wanted to, without having to get a warrant, because it could only be said to have acquired or obtained them, in the legal sense, if and when the agency “searched for and retrieved” them from its database.

- America’s fundamental laws exist to make the job of law enforcement not easier but harder. This isn’t a bug, it’s a core feature of democracy.

- Among the most important of these restraints are the prohibitions against law enforcement surveilling private citizens on their property and taking possession of their private recordings without a warrant.

- According to Maryland Criminal Law Section 10-501, adultery is illegal and punishable by a $10 fine.

- Imagine it: all the secrets big and small that could end your marriage, end your career, poison even your closest relationships, and leave you broke, friendless, and in prison.

- To refuse to claim your privacy is actually to cede it, either to a state trespassing its constitutional restraints or to a “private” business.

- Saying that you don’t need or want privacy because you have nothing to hide is to assume that no one should have, or could have, to hide anything—including their immigration status, unemployment history, financial history, and health records.

- Ultimately, saying that you don’t care about privacy because you have nothing to hide is no different from saying you don’t care about freedom of speech because you have nothing to say.

- The guy who started the Arab Spring was almost exactly my age. He was a produce peddler in Tunisia, selling fruits and vegetables out of a cart. In protest against repeated harassment and extortion by the authorities, he stood in the square and set fire to his life, dying a martyr.

- the NSA had secretly interpreted this authorization as a license to collect all of the “business records,” or metadata, of telephone communications coming through American telecoms, such as Verizon and AT&T, on “an ongoing daily basis.”

- PRISM enabled the NSA to routinely collect data from Microsoft, Yahoo!, Google, Facebook, Paltalk, YouTube, Skype, AOL, and Apple, including email, photos, video and audio chats, Web-browsing content, search engine queries, and all other data stored on their clouds,

- Upstream collection, meanwhile, was arguably even more invasive. It enabled the routine capturing of data directly from private-sector Internet infrastructure—the switches and routers that shunt Internet traffic worldwide, via the satellites in orbit and the high-capacity fiber-optic cables that run under the ocean.

- If TURMOIL flags your traffic as suspicious, it tips it over to TURBINE, which diverts your request to the NSA’s servers. There, algorithms decide which of the agency’s exploits—malware programs—to use against you.

- American law makes no distinction between providing classified information to the press in the public interest and providing it, even selling it, to the enemy.

- the Government Communications Headquarters, or GCHQ, which was setting up dragnets like OPTICNERVE, a program that saved a snapshot every five minutes from the cameras of people video-chatting on platforms like Yahoo Messenger,

- one of the IT directors, who stopped me and asked me what I needed it for—he’d been a major proponent of getting rid of them. “Stealing secrets,” I answered, and we laughed.

- What united our audience wasn’t an interest in Tor, or even a fear of being spied on as much as a desire to re-establish a sense of control over the private spaces in their lives.

- encryption is the single best hope for fighting surveillance of any kind.

- The program that enabled this access was called XKEYSCORE, which is perhaps best understood as a search engine that lets an analyst search through all the records of your life.

- I realized, as one of them was explaining to me the details of his targets’ security routines, that intercepted nudes were a kind of informal office currency, because his buddy kept spinning in his chair to interrupt us with a smile, saying, “Check her out,” to which my instructor would invariably reply “Bonus!” or “Nice!”

- One thing you come to understand very quickly while using XKEYSCORE is that nearly everyone in the world who’s online has at least two things in common: they have all watched porn at one time or another, and they all store photos and videos of their family.

- I think everybody has had this kind of experience: the more conscious you are of being recorded, the more self-conscious you become.

- as Hemingway once wrote, the way to make people trustworthy is to trust them.

- WE LANDED AT Sheremetyevo on June 23 for what we assumed would be a twenty-hour layover. It has now dragged on for over six years. Exile is an endless layover.

- All told, we were trapped in the airport for a biblical forty days and forty nights.

- How can we talk like normal people when they’re eavesdropping on all our calls?

- But I remember the guide at Kilauea saying that volcanoes are only destructive in the short term. In the long term, they move the world.

- The year 2016 was a landmark in tech history, the first year since the invention of the Internet that more Web traffic was encrypted than unencrypted.

- my work heading the Freedom of the Press Foundation,

- Universal Declaration of Human Rights, whose Article 12 states: “No one shall be subjected to arbitrary interference with his privacy, family, home or correspondence, nor to attacks upon his honor and reputation.
