:PROPERTIES:
:ID:       b2e7e622-7931-49c9-9bbf-d27970ff8098
:END:
#+setupfile: ../../hugo_setup.org
#+title: The Untethered Soul

- author :: Jefferson Singer
- tags :: [[id:25648458-9346-4332-8744-482ef91e6bf5][Mindfulness]]
- rating :: 5/5
  
* Review

#+BEGIN_QUOTE
“Most people just go from day to day protecting themselves and making sure nothing goes too wrong.”
#+END_QUOTE

This is a book about listening—listening to yourself and to the constant flows of energy within your mind. The author does a fantastic job of explaining the universal principles of spiritually and [[id:25648458-9346-4332-8744-482ef91e6bf5][Mindfulness]] while separating them from the mystical words with which they are often accompanied. Here are the most important lessons:

1. You are not your thoughts; you are the one who listens. We all have a constant barrage of voices inside of our heads, and it can be challenging to determine which of them is really us. The truth is that none of them are really us—we are the awareness at the centre who is constantly watching and listening.
   
2. We are rarely aware of ourselves. We spend so much of the time trying to control the world around us and our thoughts that we almost never realize who we really are.
   
3. We are controlled by pain. All the struggles we face in life are a result of past trauma upon which we have closed. The secret to freedom is to never close, allowing life's disturbances to flow through us like water.

Like many books of this genre, a simple summary does not do justice to the experience of reading this book. While it left me moderately disturbed on an intellectual level, I found it moving.

* Highlights

- True personal growth is about transcending the part of you that is not okay and needs protection.

- Your inner growth is completely dependent upon the realization that the only way to find peace and contentment is to stop thinking about yourself.

- There are two distinct aspects of your inner being. The first is you, the awareness, the witness, the centre of your willful intentions; and the other is that which you watch. The problem is, the part that you watch never shuts up.

- Ramana Maharshi (1879-1950), a great teacher in the yogic tradition, used to say that to attain inner freedom one must continuously and sincerely ask the question “Who am I?”

- The essence of consciousness is awareness, and awareness has the ability to become more aware of one thing and less aware of something else.

- In fact, you are so preoccupied with controlling your world of thoughts, emotions, and physical sensations that you don’t even know you’re in there.

- The only reason you don’t feel this energy all the time is because you block it. You block it by closing your heart, by closing your mind, and by pulling yourself into a restrictive space inside.

- Energy doesn’t get old, it doesn’t get tired, and it doesn’t need food. What it needs is openness and receptivity.

- The more you learn to stay open, the more the energy can flow into you. You practice opening by not closing. Any time you start to close, ask yourself whether you really want to cut off the energy flow.

- What you’ll find is that the only thing you really want from life is to feel enthusiasm, joy, and love.

- The most important thing in life is your inner energy. If you’re always tired and never enthused, then life is no fun. But if you’re always inspired and filled with energy, then every minute of every day is an exciting experience. Learn to work with these things.

- That is how an awakened being lives in the “now.” They are present, life is present, and the wholeness of life is passing through them.

- When the energy can’t make it through the mind because of conflicts with other thoughts and mental concepts, it then tries to release through the heart. That is what creates all the emotional activity.

- The alternative is to enjoy life instead of clinging to it or pushing it away. If you can live like that, each moment will change you. If you are willing to experience the gift of life instead of fighting with it, you will be moved to the depth of your being.

- don’t close,

- When you close down and protect yourself, you are pulling a shell around the part of you that is weak.

- Most people just go from day to day protecting themselves and making sure nothing goes too wrong.

- The moment you see the energy getting imbalanced inside, the moment you see the heart starting to tense and get defensive, you just stop.

- If you aren’t centered, your consciousness is just following whatever catches its attention.

- No matter what events take place in life, it is always better to let go rather than to close.

- Always let go as soon as you’re aware that you didn’t.

- The signs of the body breaking are pain and weakness. The signs of the psyche breaking are underlying fear and incessant neurotic thought.

- A naturally healthy body is one that just does what it’s supposed to do while you’re going about your business. You never have to think about it.

- The mind is simply a computer, a tool. It can be used to ponder great thoughts, solve scientific problems, and serve humanity. But you, in your lost state, told it to spend its time conjuring up outer solutions for your very personal inner problems. You are the one who is trying to use the analytical mind to protect yourself from the natural unfolding of life.

- The key is to be quiet. It’s not that your mind has to be quiet. You be quiet. You, the one inside watching the neurotic mind, just relax.

- Just be there, noticing that you notice.

- Inner pain is always there, underneath, hidden by the layers of our thoughts and emotions.

- You must look inside yourself and determine that from now on pain is not a problem. It is just a thing in the universe. Somebody can say something to you that can cause your heart to react and catch fire, but then it passes.

- That is what all the noise is inside your mind: an attempt to avoid the stored pain.

- What if consciousness were to remove its focus from your personal set of thoughts, your personal set of emotions, and your limited sensory input?

- Time and again, every day, the natural flow of life collides with our walls and tries to tear them down. But time and again, we defend them.

- You can get out simply by letting everyday life take down the walls you hold around yourself. You simply don’t participate in supporting, maintaining, and defending your fortress.

- there’s a reason you overeat.

- When you are trained, like a great athlete, to immediately relax through your edges when they get hit, then it’s all over. You realize that you will always be fine.

- You end up loving your edges because they point your way to freedom. All you have to do is constantly relax and lean into them.

- You must be willing to see that this need to protect yourself is where the entire personality comes from.

- You’re just on a planet spinning around the middle of absolutely nowhere. You came here to visit for a handful of years and then you’re going to leave. How can you live all stressed-out over everything? Don’t do it.

- “Do you want to be happy or not?” If you keep it that simple, you will see that it really is under your control. It’s just that you have a deep-seated set of preferences that gets in the way.

- It’s not a question of whether your happiness is under your control. Of course it’s under your control. It’s just that you don’t really mean it when you say you’re willing to stay happy.

- Why shouldn’t you be happy? You gain nothing by being bothered by life’s events. It doesn’t change the world; you just suffer.

- Instead of complaining, you’re just having fun with the different situations that unfold.

- For instance, if somebody says something that we don’t like, obviously our resistance won’t stop them from having said it. What we’re really resisting is the experience of the event passing through us.

- The way to work with resistance is by relaxing.

- This process of relaxing through resistance is beneficial to everything in your life.

- Let’s say you’re living life without the thought of death, and the Angel of Death comes to you and says, “Come, it’s time to go.” You say, “But no. You’re supposed to give me a warning so I can decide what I want to do with my last week. I’m supposed to get one more week.” Do you know what Death will say to you? He’ll say, “My God! I gave you fifty-two weeks this past year alone. And look at all the other weeks I’ve given you. Why would you need one more? What did you do with all those?”

- You have to understand that it is your attempt to get special experiences from life that makes you miss the actual experience of life.

- Unfortunately, spiritual teachings often mask the essence of truth with mystical words.

- So where is the Tao? The Tao is in the middle. It’s the place where there is no energy pushing in either direction. The pendulum has been permitted to come to balance concerning food, relationships, sex, money, doing, not-doing, and everything else.

- Remember, whoever remains present with fixity of purpose comes out on top in the end.

- If you say to God, “I don’t believe in you and want nothing to do with you,” creation continues to sustain you.
