:PROPERTIES:
:ID:       ff9c2864-1f26-478b-9a25-98cc1e858df3
:ROAM_ALIASES: "\"GWAS\""
:END:
#+setupfile: ../hugo_setup.org
#+title: Genome-wide Association Study (GWAS)


- A large number of genetic variants-typically SNPs (hundreds of thousands to millions) are tested across many individuals to identify genotype-phenotype associations.
- Usually SNPs are analyzed, although other types of mutations are possible.
- The SNPs of controls and those with a particular disease are analyzed. GWAS looks for mutations which only occur in patients with that particular disease.

* Benefits
- Effective at discovering SNV-trait associations.
- Has successfully identified mutations which increase risk for:
  - Major depressive disorder
  - Several types of cancers
  - Type 2 diabetes
  - Schizophrenia
  - and others…

* Limitations
- It is challenging to determine whether or not there is a cause-and-effect relationship between mutations and phenotype.
- Limited to single-base mutations.
- SNPs are often markers of nearby regions of the genome where the disease-causing mutation lies—they may not themselves be responsible.
