:PROPERTIES:
:ID:       745e9fef-c07d-4e96-98aa-3016c5888990
:END:
#+setupfile: ../hugo_setup.org
#+title:The value of reading

 #+begin_quote
If you love to read, or learn to love reading, you will have an amazing life. Period. Life will always have hardships, pressure, and incredibly annoying people, but books will make it all worthwhile. In books, you will find your North Star, and you will find you, which is why you are here.
​
Books are paper ships, to all the worlds, to ancient Egypt, outer space, eternity, into the childhood of your favorite musician, and — the most precious stunning journey of all — into your own heart, your own family, your own history and future and body.
​
Out of these flat almost two-dimensional boxes of paper will spring mountains, lions, concerts, galaxies, heroes. You will meet people who have been all but destroyed, who have risen up and will bring you with them. Books and stories are medicine, plaster casts for broken lives and hearts, slings for weakened spirits. And in reading, you will laugh harder than you ever imagined laughing, and this will be magic, heaven, and salvation. I promise.
 — Anne Lamott
 #+end_quote


