:PROPERTIES:
:ID:       cd1aa9a0-ca77-4cae-b880-17ebda7c2ae7
:END:
#+setupfile: ../hugo_setup.org
#+title:What classes should be taught in school?

* Mandatory classes

- Coding and [[id:690198da-5662-4141-a601-f93229f90675][Digital Privacy]] :: society is increasingly technology-dependent, and digital literacy /must/ become a core component of our education system.

- Basic life skills :: money, relationships, emotional intelligence.

- Physical education :: should be performed twice a day.

- Math ::

- Theatre :: theatre teaches kids how to communicate, how to refine a sense of humour, and how to get along with other people.

- Music /or/ a language :: music is a language, and students who learn languages are vastly more capable than those who don't.

* Other classes to consider

- Meditation :: kids are never taught how to sit still and reflect. By having them sit quietly for half an hour every day, it is likely that many of them could learn to manage their restlessness and anxiety.


* Classes to abolish

- English :: While written and oral communications skills are vital, they should be integrated elsewhere in the curriculum. Grammar is learned through use and poetry/literature are of little importance compared to other topics.

- Chemistry / Biology ::



* Other

More importantly, [[id:cebe9120-291d-42a7-a408-f324d85deed0][Teachers should be payed more]]
