#+TITLE: Making Black Women Scientists under White Empiricism: The Racialization of Epistemology in Physics
#+ROAM_KEY: cite:prescod-weinsteinMakingBlackWomen2020

- tags :: [[file:../racial_inequality_in_western_societies.org][§Racial Inequality in Western Societies]]
- keywords :: 
- author :: Prescod-Weinstein, Chandra

  
- The author argues that in physics, the once principled system of scientific reasoning has been contaminated by racial and gender biases.

- She introduces the concept of /white empiricism/ —the flawed belief that certain groups of people, especially white men, have a capacity for objectivity not found in other groups of people, especially black women.

- While white men are expected to be able to self-evaluate for bias, the research and experiences of black women are considered to be incompetent and are not given due consideration.

- These white men have an intrinsic belief that they are free from bias, going so far as to fail to apply the scientific method to their research while selectively resisting the entry of black women into physics.

- Fewer than one hundred black American women have been granted PhDs from a department of physics or astronomy.

- These men claim that physics is a ``culture of no culture'', a phrase that is used to discredit any potential criticism against field.

- Nowadays, physicists use this term to posture that a black woman can work in physics, while ignoring the barriers that make it possible for her to become one.

- High energy physics is regarded as the most prestigious branch of physics, and the developing subdiscipline of quantum gravity is a the forefront of this research.

  - Even within physics, high energy physics is especially white and especially male.

  - Within this field, there is a correlation between aggression and success, and more objectively rational theories are overshadowed by weak theories backed by confidence.

  - String theory—a proposed theory that would unify the four fundamental forces—is an example of this asymmetry.
    - Recently, there has been a lack of empirical evidence to support many of its claims. Rather than to admit that this may be due to a lack of heterogeneity and inclusion within the field, many researchers are contemplating abandoning the scientific method—the epitome of scientific reasoning—in favour of a purely logical, unsubstatiable approach.

    - This bias fundamentally alters to 

* Highlights

- In this article, I propose that race and ethnicity impact epistemic outcomes in physics, despite the universality of the laws that undergird physics, and I introduce the concept of white empiricism to provide one explanation for why.

- Essentially, white empiricism involves a predominantly white, predominantly male professional community selectively failing to ap- ply the scientiﬁc method to themselves while using “scientiﬁc” evaluation to strengthen the barriers to Black women’s entry into physics.

- Martin compellingly argues that high energy physics is often reported in terms of intellectual achievement while condensed matter is simply reported as tech- nological evolution—whereas in reality, per Sharon Traweek, prestige in phys- ics is determined by ﬁnely tuned social dynamics through which scientists’ identities are made (e.g., Traweek 1992, 90).

- Just as Londa Schiebinger wondered about science, Amy Graves (née Bug) once asked, “Has feminism changed physics?” (Schiebinger 1999; Bug 2003). Her answer was, “Not yet,” and although incremental work on this question continues, it seems that the answer is still, at the very least, “not much” (Rolin 1999, 2006; Harrell 2016).

- There are clear indicators that feminism has changed other scientiﬁc ﬁelds, particularly the life sciences (e.g., Haraway 1988; Wylie 2003; Arnold 2017).

- Yet Traweek’s par- ticle physicists (interchangeably known as high energy physicists) imagine themselves to be unshackled by this history, as participants in a “culture of no culture” (Traweek 1992, 162).

- Notably, the majority of Black American women who have earned PhDs in physics, astronomy, and related ﬁelds have done so in areas on the “wrong” side of prestige asymmetry (see, e.g., Valentine 2018).

- The most highly esteemed ﬁeld, high energy physics theory (which covers particles, quantum gravity, and some aspects of cosmology and nuclear physics), has only seen about six completed PhDs by Black American women, with a greater (although still disproportionately low) number going to Black men.

- Testimonial injustice is the act of deval- uing a speaker’s word due to prejudices against the identity group to which the speaker belongs. Hermeneutical injustice focuses on a lack of access to resources, leading knowers to question their own competence.

- Concep- tual competence injustice can be seen as a speciﬁc form of epistemic oppression whereby a knower is seen as fundamentally lacking the necessary conceptual or linguistic competence to be regarded as a knower (Anderson 2017).

- A scientist who believes in value-free science—the “culture of no culture” identiﬁed by Traweek—can look around and notice a community primarily comprised of white men, instigating an analytic decision (1992, 162).

- Moulton succinctly notes in a section title that in philosophy there is an “unhappy conﬂation of aggression with success,” and Traweek ob- serves the same among American high energy physicists (Moulton 1983, 149; Traweek 1992, 130).

- Misogynoir can take the form of epistemic exploitation, where Black women are expected to educate colleagues and acquaintances about their experiences with sexism and racism (Berenstain 2016; Dancy, Edwards, and Davis 2018).

- White em- piricism is therefore also a tripling down on epistemic exploitation: it involves both exclusion and a demand for labor to explain the experience of exclusion and then disbelief in response to the victim’s testimony (Langton 2000; Gu- tiérrez y M…

- For many people working in particle phys- ics and cosmology, a complete, widely accepted theory of quantum gravity is a holy grail: can one uniﬁed theory explain both quantum mechanics and general relativity simultaneously, despite apparent inconsistencies?

- In the absence of empirical support, should support for research in string theory come to an end?

- The scientiﬁc method overly constrains our models to meet certain requirements that no longer serve the needs of physics theory.

- Holbrook holds that Black students are presumed to be epistemically unreliable on the subject of racism, which sends the message that they can never achieve an objective observer status akin to that of their white peers.

- In effect, white physicists are considered competent to self-evaluate for bias against other epistemic agents and theories of physics where there is no empirical grounding to as- sist in decision making, while Black epistemic agents are considered incom- petent to bring a lifetime of knowledge gathering about race and racism to bear on their everyday experiences. This empirical adjudication is the phe- nomenon of white empiricism.

- In all of American history, fewer than one hundred Black Amer- ican women have earned a PhD from a department of physics, a department of astronomy, or a department of physics and astronomy, even though about two thousand PhDs in physics are granted in the United States every year, with half of those going to US citizens (American Institute of Physics 2013; Valentine 2018).

- My own experience with the sexual misconduct rumor mill in science indicates that Brown’s experience is not singular, yet there is little research on the way Black women are speciﬁcally targeted by men who may not feel safe similarly harassing white women, making it difﬁcult to fully grasp the extent of the problem.

- Race and gender are social constructions laden with social values and interests, and race in partic- ular was speciﬁcally developed to serve white supremacist values and interests.

- Returning to the question of whether a Black woman can be a physicist, the community now responds more positively while failing to address the structural dynamics that make it difﬁcult for her to become and remain one.

- Rather than confront this reality, the dominant majority instead persists in a white empiricism that publicly insists that identity fundamentally does not matter while embedding identity into the culture.

- Evelyn Fox Keller talks about Western ep- istemic constructions of science as “male” and nature as “female,” leading to what Banu Subramaniam and Mary Wyer have called “dementoring”—the training of women in STEM by “untraining them as women” and assimilat- ing them as scientists…

- Vera Rubin, widely held to be the ﬁrst astronomer to ﬁnd widely accepted evidence for the elusive dark matter (which should be called clear matter), pursued this particular research direction when a combination of sexism and masculinist behavior made it di…

- The central argument of this article is that white empiricism limits who is authorized to make claims about physics and that this is damaging to phys- ics and alters its empirical direction.

- Through the recognition of white empiricism, a bifurcated logic that serves white supremacist traditions in science while deontologizing margin- alized Black women physicists, I propose that the Black feminist theory intersectionality should change physics—and not just through who be- comes a physicist but through the actual outcomes of what we come to know.

  
