:PROPERTIES:
:ID:       47872b91-895f-473a-a288-e8084494167e
:ROAM_REFS: cite:hoffmanRacialBiasPain2016
:END:
#+setupfile: ../../hugo_setup.org
#+TITLE: Racial bias in pain assessment and treatment recommendations, and false beliefs about biological differences between blacks and whites



- keywords :: WRDS150
- author :: Hoffman, K. M., Trawalter, S., Axt, J. R., & Oliver, M. N.

  - Within the American healthcare system there is a systematic undertreatment of pain for black patients. For example, previous research has shown that black patients are 17% less likely to receive analgesics in the emergency room for extremity fractures and are less likely to receive medication—especially opioids—for pain.

  - To extend on this previous research, this study attempts to quantify the relation between the racial misconceptions of both laypeople and medical students about the strength of black people's bodies with the undervaluation and undertreatment of their pain.

  - Two studies were conducted, evaluating how the false biological beliefs about black people harboured by both individuals without medical training and medical students respectively affect their perception of black patients' pain. These beliefs included "blacks' nerve endings are less sensitive than whites'", "blacks' skin is thicker than whites'", and "Blacks have stronger immune systems than whites".
    
    - The first study comprised of 121 white, American-born, English-speaking laypeople. They were first asked to rate the amount of pain they would experience in eighteen different scenarios. Then, they were asked to rate the pain that either a white or a black patient would experience for each of the same scenarios. Finally, they were asked to rate the truthfulness of fifteen different statements about the biological differences between whites and blacks, only some of which were accurate.

    - It was shown that 73% percent of participants endorsed at least one false statement. Furthermore, while participants that didn't endorse any false statements rated blacks pain as being equal to that of whites, those that endorsed more false statements rated blacks pain as being lesser than whites.

    - A similar study was then repeated on a sample of 222 white, American-born, English-speaking medical students and residents. The participants were asked to rate the pain of a black and white patient in two mock medical scenarios and to make subsequent medical recommendations. They were then asked to rate the truthfulness of the same fifteen statements about the biological differences between whites and blacks from study 1.

    - Approximately 50% of participants endorsed at least one false belief, and the majority of those who did both rated the black patient's pain as being less than they white patient's recommended less accurate treatment.
      - Surprisingly, the opposite racial bias was also observed—participants who endorsed fewer false beliefs rated the white patient's pain as being less than the black patient's, although on average they recommended the same treatment for both patients.

      - Regardless, this study conclusively demonstrates that pain management in the American healthcare system is racially biased and that black patients are systematically undertreated for pain.

    - Limitations in these studies that may provide stimulus for further research include the use of survey techniques for reporting, small sample sizes, and the lack of research on medical professionals beyond medical students and residents
