#+TITLE: The opioid crisis in black and white: the role of race in our nation's recent drug epidemic
#+ROAM_KEY: cite:omOpioidCrisisBlack2018

- tags :: [[file:../racial_bias_in_the_treament_of_drug_epidemics.org][§Racial Bias in the Treament of Drug Epidemics]]
- keywords :: WRDS150
- author :: Om, A.

- In 1996 the American Pain Society introduced the concept of 'pain as the fifth vital sign'. Since pain is subjective, this led to over-prescription of opioids to combat perceived pain.

- When drug crises disproportionately affect white Americans, public opinion and government policy treats it as a public health crisis. When black populations are more severely impacted, however, it is treated as a criminal problem.
  - The opioid crisis mostly affects white populations. Consequently, only 9% called for criminal justice approaches.

- While African Americans and white Americans use illicit drugs at similar rates, African Americans are ten times more likely to be incarcerated for drug use.
