:PROPERTIES:
:ID:       d1955467-079b-450c-8943-bdad843c61ba
:ROAM_REFS: cite:omOpioidCrisisBlack2018
:END:
#+setupfile: .../hugo_setup.org
#+TITLE: The opioid crisis in black and white: the role of race in our nation's recent drug epidemic


- tags :: [[id:a1a36ae3-a7fb-4806-9e28-3a9ed4d22edc][§Racial Inequality in Western Societies]]
- keywords :: WRDS150
- author :: Om, A.

- In 1996 the American Pain Society introduced the concept of 'pain as the fifth vital sign'. Since pain is subjective, this led to over-prescription of opioids to combat perceived pain.

- When drug crises disproportionately affect white Americans, public opinion and government policy treats it as a public health crisis. When black populations are more severely impacted, however, it is treated as a criminal problem.
  - The opioid crisis mostly affects white populations. Consequently, only 9% called for criminal justice approaches.

- While African Americans and white Americans use illicit drugs at similar rates, African Americans are ten times more likely to be incarcerated for drug use.
