#+TITLE: Why conversation is not the soul of democracy
#+ROAM_KEY: cite:schudsonWhyConversationNot1997

- tags ::
- keywords :: WRDS150
- author :: Schudson, M.
  
- In the 20th century, the press separated itself from public conversation in the name of objectivity.
  - "The press no longer facilitated or animated a public conversation, for public conversation had disappeared." [[cite:munsonJamesCareyCritical1997][p. 246]
  - Mine: nowadays, however, the press /is/ the public.
    - How can we restore objectivity to public discussion.

- Schudson proposes two models of conversation, the sociable model and the problem-solving model
  
  - The sociable model is pleasurable and non-utilitarian.

  - The problem-solving model is rooted in the exploration of issues to achieve a common goal.

- In 1927, John Dewey argued that systems that are now synonymous with democracy such as popular voting and majority rule were popularized because they mandate conversation and debate. cite:dewey1954public He believed that "the improvement of the methods and conditions of debate, discussion, and persuasion [is] /the/ problem of the public" (p. 208).

- Government itself should be rooted in problem-solving conversation.

- While civility is often associated with productive debate, Schudson believes that in democracy, civility is often counterproductive.
  - "Democracy may sometimes require that your interlocutor does not wait politely for you to finish but shakes you by the collar and cries 'Listen! Listen for God's sake!'" (p. 308).

  - This withdrawal from civility is often associated with manifestations and strikes.

My thoughts: In the modern era, government has become intertwined with sociable conversation. Nowadays, politicians all have Twitter accounts and such conversation is no longer secluded to groups of friends but is public for the world to see.
  
* Annotations

"In the twentieth century, as journalism became more "objective" according to its professional lights, the relationship of press and public disintegrated. "The press no longer facilitated or animated a public conversation for public conversation had disappeared" (1995, p. 389)." (Schudson 1997:299)

"Recognizing a tension between principles in conversation is one way to arrive at a more coherent and realistic view of conversation. I propose, alternatively, that two rather different ideals of conversation are intertwined and confused. One ideal could be termed the sociable model of conversation, the other the problem-solving model. The distinguishing feature of the sociable ideal is its insistence that conversation be non-utilitarian." (Schudson 1997:300)

"this model, then, conversation is oriented to the pleasure of interacting with others in conversation itself; it is therefore contemporaneously social." (Schudson 1997:301)

"Popular voting, majority rule, and other indices of democracy are vouched for, John Dewey wrote, by the fact that "they involve a consultation and discussion which uncover social needs and troubles" (1927, p. 206) The central problem for modern democracies to face is "the improvement of the methods and conditions of debate, discussion and persuasion. That is the problem of the public." (p. 208)" (Schudson 1997:301)

"The problem-solving model sees conversation as a means to the end of good government. More strongly, it pictures conversation itself as a model of good government" (Schudson 1997:301)

"Third, democracy may require withdrawal from civility itself. Democracy may sometimes require that your interlocutor does not wait politely for you o finish but shakes you by the collar and cries "Listen! Listen for God's sake!"" (Schudson 1997:309)
