#+title: Active Recall

Active recall is reading with intention, asking yourself how the information connects to what you already know, and testing yourself on what you learn.

_In short, active recall is about spending less time on the input side of learning (reading, listening, taking notes) and spending more time on the output side (testing yourself, producing work)._

#+BEGIN_QUOTE
“When you read a book, you haven't learned anything. You have a plan, that's it. Only when you put in into practice do you know whether you've learned anything.”

—[[file:tiago_forte.org][§Tiago Forte]] 
#+END_QUOTE

#+BEGIN_QUOTE
“Remembering and idea is some combination of the number of connections you can draw and [[file:spaced_repetition.org][§Spaced Repetition]]”

— Simon Eskildsen
#+END_QUOTE

- According to cite:bjork, effective learning is often unintuitive.
  - It is easy to be misled into thinking that we are using effective learning techniques, such as highlighting and rereading, when we are *merely becoming more familiar with the material, not learning it.*
- There is a distinction between current performance and learning.
  - It is very possible to have high performance without learning (such as cramming), and vice-versa.
- There is a key distinction between *storage strength* and *retrieval strength*.
  - storage strength :: how well ingrained our [[file:mental_representations.org][§Mental Representations]] are of a given topic.
    - Storage strength is accumulated; it never decreases.
  - retrieval strength :: the ease with which we can *currently* access these mental representations.
    - Retrieval strenght decreases with time.
    - *Current performance is entirely a function of retrieval strength.*
    
- When studying, the worse our current retrieval strength, the greater our storage strength increases. Thus, it is favourable to introduce *desirable difficulties* to our learning.
  - This is the principle behind [[file:spaced_repetition.org][§Spaced Repetition]]— _ideally, we should revisit a topic just as we are about to forget it._
    
Desirable difficulties can be introduced in several ways:
1. *By learning under novel conditions:* our ability to retrieve information is influenced by the environments in which we have practiced it. By varying study conditions, we maximize the chance that we will be able to recall the information in a novel environment.
   - For example, study in two different libraries.
     
2. *By applying [[file:spaced_repetition.org][§Spaced Repetition]].*

3. *By interleaving your practice:* Alternate between subjects, and when studying a particular subject, alternate between different methods of studying.
   - For example, when studying math, alternate between textbook questions and practice tests.

   - *Interleaving forces us to repeatedly reload our mental representations of a topic. When be perform blocked practice, these mental representations are constantly in memory, and are not being strengthened.*

4. *By generating solutions before they are presented to you:* This comprises two tenets:
   1. Try to solve a problem of a particular type before being presented with the solution. When you do learn the steps to solving it, you brain will be primed to remember it.

   2. Never look up an answer when, given time, you could come up with it yourself.

   #+BEGIN_QUOTE
   “Any time that you, as a learner, look up an answer of have somebody tell you or show you something that you could, drawing on current cues and your past knowledge, generate instead, you rob yourself of a powerful learning opportunity.”

   — cite:bjork
   #+END_QUOTE

bibliography:./bib/active-recall.bib

