#+TITLE: Consistency

* Ali Abdaal - A Reminder about Consistency

Hey friends,

Two minutes ago, I was snuggled up in bed under my newly-laundered sheets, hoping to get 7.5 hours of sleep before starting a week of on-calls tomorrow morning. I said ‘Hey Siri, lights off in the bedroom’ and the lights dimmed to black. I rolled over with my eyes closing, bedside fan blowing cool air on my face and thought 'this is going to be a fun week at work’.

Then, out of the blue, I realisation hit me like Hermione slapping Malfoy in The Prisoner of Azkaban. 'Oh no, it’s Sunday and I haven’t written this week’s email newsletter’.

Part of me thought 'it’s fine, you’re tired and in bed and you need a good night’s sleep. No one’s going to care about a single missed email. Just skip it this week’.

But the better part of me thought 'You’ve been doing these weekly emails for 95 weeks now, and you haven’t missed a single one. Don’t let today be the first’.

And so here we are.

I wrote about this exact conundrum in a May 2018 issue of this newsletter sent to 790 subscribers (we’re now at over 23,214).
#+BEGIN_QUOTE
I imagine no one will care about something as trivial as a missed email, but I feel that when it comes to building productive habits, consistency and ‘just showing up’ is really important. 

Lets say we’re making a commitment to ourselves that we’ll go to the gym every other day, or that we’ll study for our A-levels every day, or anything like that. We’re definitely going to have days where we can’t be bothered. We’ll make up dubious reasons, telling ourselves that one missed day doesn’t matter and that we’ll work twice as hard the following day to make it up.

This is a trap. Habits are built on consistency. The way I see it, it doesn’t really matter what we do at the gym, as long as we just show up. We can reduce the intensity of our workout, we can even just do a few stretches while watching YouTube videos, but as long as we’ve showed up, that’s what matters. 
#+END_QUOTE


So consider this email your annual reminder from me that showing up consistently is one of the best things you can do for whatever you’re working on.

Have a great week!

Ali
