#+setupfile: ../hugo_setup.org
#+title: Daily Highlight

The daily highlight is a concept introduced in [[file:books/make_time.org][§Make Time]]. They believe that in order to maximize [[file:happiness.org][§Happiness]] and [[file:productivity.org][§Productivity]], it is important to chose a single focus for the day.

  - Optimize your daily highlight for urgency, satisfaction, and joy.

  - By choosing a daily highlight that aligns with your [[file:goal_setting.org][§goals]], you take ownership of your time and prioritize your needs, not those of others.

  - [[file:ali_abdaal.org][§Ali Abdaal]] has also spoken to the benefits of what he calls the "power hour", an one period that he takes each day to work exclusively on an important-but-not-urgent task.

    #+begin_quote
    Recently I’ve started this thing called Power Hour, which involves spending an hour in the morning, before checking any emails or notifications, straight after breakfast and coffee, to exclusively work on the “Important but not Urgent” stuff.

    So in that hour, even if I’ve got a sponsored video deadline for the following day, I’m not allowed to do anything that’s urgent. Only the stuff that’s important, but that doesn’t have a looming deadline. 

    This has been game-changing. Since starting this 2 weeks ago I’ve made so much progress on an exciting new project - I’ll tell you more about that next week. And because the stuff that’s urgent always gets done anyway, I haven’t let any truly urgent things fall through the cracks. 
    #+end_quote

