:PROPERTIES:
:ID:       0cbe7b70-cbda-47c8-8e0a-d36ef0d9d794
:END:
#+setupfile: ../hugo_setup.org
#+title: Daily Highlight

Nowadays, society associates productivity with busyness. The more tasks we complete in a given time, the more productive we are perceived to be. What we lose, however, is our ability to discern which of these tasks are truly important.

According to the authors of [[id:989b6521-6410-492e-b9a4-0997337a618c][§Make Time]], the secret to making progress on the projects that you never seem to have time for is to dedicate an hour each day to work on them. This /daily highlight/, as they call it, forces you to decide for yourself what is most important and to work towards it irrespective of all the other urgent but less meaningful work you have to do.

Naturally, your highlight will not be the only task your work on throughout the day, but it will the most important. This allows you to decide for yourself what your priorities are, instead of simply reacting to those of other people.

  - Optimize your daily highlight for urgency, satisfaction, and joy.

  - By choosing a daily highlight that aligns with your [[id:63f189f8-4cc2-4f29-b263-ec3cc4f52c6a][§goals]], you take ownership of your time and prioritize your needs, not those of others.

  - [[id:8afb5c33-db02-426f-9d8b-fe283b555cd5][§Ali Abdaal]] has also spoken to the benefits of what he calls the "power hour", an one period that he takes each day to work exclusively on an important-but-not-urgent task.

    #+begin_quote
    Recently I’ve started this thing called Power Hour, which involves spending an hour in the morning, before checking any emails or notifications, straight after breakfast and coffee, to exclusively work on the “Important but not Urgent” stuff.

    So in that hour, even if I’ve got a sponsored video deadline for the following day, I’m not allowed to do anything that’s urgent. Only the stuff that’s important, but that doesn’t have a looming deadline. 

    This has been game-changing. Since starting this 2 weeks ago I’ve made so much progress on an exciting new project - I’ll tell you more about that next week. And because the stuff that’s urgent always gets done anyway, I haven’t let any truly urgent things fall through the cracks. 
    #+end_quote
