#+setupfile: ../hugo_setup.org
#+title: Deliberate Practice

- It is often assumed that improvement takes place naturally as a result of repetition. This is not true.
- Repetition leads to stagnation and eventual decline.
- To effectively improve, one must incorporate the principles of deliberate practice.

* Deliberate practice vs purposeful practice.

Technically, according to the author's of [[file:books/Peak.org][§Peak]], there is a distinction between purposeful practice and deliberate practice.

Purposeful practice:
1. Has well-defined, specific goals.
2. Is focused.
3. Involves feedback.
4. Gets you out of your comfort zone.

While deliberate practice, expanding on top of purposeful practice:
1. Develops skills that have /already/ been mastered by experts and for which effective training techniques have already been developed.
2. Incorporates expert instructors to guide a student's practice and provide effective feedback.

However, popular culture has made the two effectively synonymous.

* Learning difficult material

[[https://www.drmaciver.com/2019/05/how-to-do-hard-things/][David R. MacIver]] proposes a framework for quickly learning challenging concepts:

1. Find an easy version of whatever you find hard.
2. Modify the easy version so that it is as hard as the challenging thing in /exactly/ one way.
3. Practice the modified version until it is easy.
4. Repeat this process until the hard thing becomes easy.

While this framework is simple, it identifies a key point: the importance of tight [[file:feedback_loops.org][§Feedback Loops]].

- When you learn, don't focus on getting it right. Instead, focus on /how/ you're performing. Then, target the /specific areas/ where you're performing poorly.
