:PROPERTIES:
:ID:       8c7dad95-3946-4dfd-a3ca-ba015d3a47ef
:END:
#+setupfile: ../hugo_setup.org
#+title: Educational Reform

It is clear that modern education is antiquated and that much of what is taught in schools is a byproduct of the early-20^th century rush to train factory workers. Students are taught to learn what others have already decided, whereas life is about making discoveries.

- Classes have not evolved to meet modern technological evolution. (see [[id:cd1aa9a0-ca77-4cae-b880-17ebda7c2ae7][§What classes should be taught in school?]])

#+BEGIN_QUOTE
“School’s don’t show you the world, they just show you a bunch of careers.”

— Michelle Obama
#+END_QUOTE

#+BEGIN_QUOTE
“Is state education designed to encourage more Darwins and Newtons, or to create middle-management civil servants and workers? What tensions are brought into being when a child’s natural proclivity to question everything in their own unique way comes into contact with a one-size-fits-all mode of education?”

— Akala
#+END_QUOTE

 - What would happen if we completely removed grades and diplomas? Would it result in a meritocracy?
