#+setupfile: ../hugo_setup.org
#+title: How to Have More Time

Busyness is now seen as a proxy for productivity. The busier we are, the more we signal accomplishment without having to actually put in the work.

Consequently, we take on more responsibilities without question.

Even when we get overwhelmed and give ourselves more time to accomplish tasks, we are no less busy—[[file:parkinson_s_law.org][§Parkinson's Law]] dictates that they will occupy all of our time regardless of how much we have.

The solution is to be deliberate with our time.

Every day, pick a highlight. Block off an hour of time and decide, for /yourself,/ what is the most meaningful work you can do during that time. #[[file:books/make_time.org][§Make Time]]
  
When we make a commitment to spend a portion of our day on tasks that are important to us, we accomplish our goals quickly. For example,
- NASA successfully launched Apollo 8 143 days after first conception
  
- [[file:derek_sivers.org][§Derek Sivers]] wrote /Anything You Want/, his bestselling book, in ten days. #[[file:writing.org][§Writing]]

- Equally, Brendan Eich wrote javascript in just ten days.

Today, I chose to write. I have homework to finish, emails to respond to, and applications to finish, but I'm taking the time this morning to write this post.

Then, once you've chosen a highlight, it's time to focus.

Focus is the most fulfilling of human experiences. The feeling of unbroken concentration interspersed with inspiration is unparalleled, and those that can reach this state frequently are successful. However, the number of distractions that vie for our attention is increasing and so we need to be proactive in removing them.

When you want to work efficiently:
- Have a specific, worthwhile task to work on.
- Tune out the outside world. Put away your phone and close old tabs.
- Take real breaks. Stretch or go sit in the sun.

If you want more, read [[file:books/make_time.org][§Make Time]], complemented by [[file:books/Deep-Work.org][§Deep Work: Rules for Focused Success in a Distracted World.]]
