#+setupfile: ../hugo_setup.org
#+title: Lateral Thinking with Withered Technology

Lateral thinking with withered technology is a term coined by Gunpei Yokoi, the original designer of the Game Boy.

The original idea for the Game Boy came to him one day while riding on a train. He saw a man next to him playing with a calculator and realized that the same technology—which was cheap and abundant at the time—could be employed to make a game console. By borrowing seasoned (withered) technology from other disciplines and finding new ways to make use of it (lateral thinking), Yokoi was able to come up with a new product that sold over 112 million units.

Lateral thinking with withered technology is equally applicable to knowledge work, and especially [[file:writing.org][§Writing]]. [[file:steve_jobs.org][§Steve Jobs]] once said that "good artists copy; great artists steal". Old ideas can be learned, remixed, and later employed in new ways to come up with fresh material.

See [[file:david_perell.org][§David Perell]]'s [[https://perell.com/note/lateral-thinking-with-withered-ideas/][article]].
