#+setupfile: ../hugo_setup.org
#+title: Love

#+BEGIN_QUOTE
“Well now really when we go back into falling in love. And say, it’s crazy. Falling. You see? We don’t say “rising into love”. There is in it, the idea of the fall. And it goes back, as a matter of fact, to extremely fundamental things. That there is always a curious tie at some point between the fall and the creation. Taking this ghastly risk is the condition of there being life. You see, for all life is an act of faith and an act of gamble. The moment you take a step, you do so on an act of faith because you don’t really know that the floor’s not going to give under your feet. The moment you take a journey, what an act of faith. The moment that you enter into any kind of human undertaking in relationship, what an act of faith. See, you’ve given yourself up. But this is the most powerful thing that can be done: surrender. See. And love is an act of surrender to another person. Total abandonment. I give myself to you. Take me. Do anything you like with me. See. So, that’s quite mad because you see, it’s letting things get out of control. All sensible people keep things in control. Watch it, watch it, watch it. Security? Vigilance Watch it. Police? Watch it. Guards? Watch it. Who’s going to watch the guards? So, actually, therefore, the course of wisdom, what is really sensible, is to let go, is to commit oneself, to give oneself up and that’s quite mad. So we come to the strange conclusion that in madness lies sanity.”

— [[file:alan_watts.org][§Alan Watts]]
#+END_QUOTE

