#+setupfile: ../hugo_setup.org
#+title: Note-Taking

- If you don't write something down or otherwise record it, you will invariably forget it. By recording your ideas, you unburden your mind from the responsibility of remembering and allow it to think.

- Kendrick Lamar takes notes to capture experiences so that he can reflect on them:

#+begin_quote
I have to make notes because a lot of my inspiration comes from meeting people or going outside the country, or going around the corner of my old neighborhood and talking to a five-year-old little boy. And I have to remember these things. I have to write them down and then five or three months later, I have to find that same emotion that I felt when I was inspired by it, so I have to dig deep to see what triggered the idea… It comes back because I have key little words that make me realize the exact emotion which drew the inspiration.

  — Kendrick Lamar
#+end_quote



- Keep your note-taking system [[file:simplicity.org][§Simple]]. Standardization allows for creativity. When we have no restrictions on the format of our thinking, our brain must think constantly about how to record its thoughts. By imposing such restrictions, we are free to focus on the content. [[file:books/How-to-Take-Smart-Notes.org][§How to Take Smart Notes]]
  - Many of the most creative people are incredibly ritualistic.

  - Nobody feels the need to add more letters to the alphabet because the 26 we have are already capable of expressing anything: from love letters, to business contracts, to revolutionary manifestos.

    #+begin_quote An undistracted brain and a reliable collection of notes is pretty much all we need. Everything else is just clutter.
    — [[file:tiago_forte.org][§Tiago Forte]]
    #+end_quote
