:PROPERTIES:
:ID:       bd71fb64-03fd-4b55-90ce-46764a191b34
:END:
#+setupfile: ../hugo_setup.org
#+title: Nuclear Fusion

- Nuclear Fusion is [[id:c15f119b-dbc7-426c-a9fa-cc8f18d546dd][§Clean Energy]]

* How does it work

When atoms are brought close together, there are two opposing forces at play: the attractive and aptly-named strong force and the repulsive electromagnetic force. The strong force only acts at very short distances, and so the challenge is to get the two nuclei close enough for it to activate. The electromagnetic force does not like this, and so an enormous amount of energy in the form of heat must be provided for fusion to occur. Only once a certain temperature threshold, called the Coulomb barrier, is achieved at around 100 million ℃ do the atoms fuse. The two hydrogen nuclei smash together and release an enormous amount of energy (~17.6 MeV).


- Fusion occurs when the nuclei of two atoms are forced close enough together that the attraction of the strong force overcomes the electromagnetic repulsion.
  - The kinetic-energy barrier required to achieve fusion is known as the Coulomb barrier
  - Requires a temperature of ~100 million K

* Evaluation
:PROPERTIES:
:ID:       c59c767d-dac8-4673-81a5-0a14e08b30d8
:END:

Reactions are evaluated using the Lawson Criterion:

Net power = Efficiency × (Fusion − Radiation loss − Conduction loss) 

1. Net power is the excess power beyond that needed internally for the process to proceed in any fusion power plant.
2. Efficiency is how much energy is needed to drive the device and how well it collects energy from the reactions.
3. Fusion is rate of energy generated by the fusion reactions.
4. Radiation loss is the energy lost as light (including X-rays) leaving the plasma.
5. Conduction loss is the energy lost as particles leave the plasma, carrying away energy.
