:PROPERTIES:
:ID:       b9c65644-01fc-4488-87d2-b41e7c87df90
:END:
#+setupfile: ../hugo_setup.org
#+title: Personalized living communities are an unexplored way of life

In his newsletter, [[id:806a7fda-b943-4160-8af1-e71c19d6f9a7][§David Perell]] proposed the idea of personalized living communities—groups of friends who rent or buy houses close together and then communally cook, host activities, and raise their kids as a group.

This would perhaps emulate the [[id:03a97f88-f4d2-4d38-997c-b63f733692ae][§University/College]] lifestyle that people so often miss when they leave school. It must be hard to make and maintain friendships as an adult, and so this way of living might provide a greater sense of community for those who participate.

Original quote:
#+begin_quote
Long-term, I've been thinking about what it'd look like to live with a group of 10-30 friends and raise our kids together. We'd get a group of houses on the same street in an affordable area, eat meals together, and co-hire tutors to homeschool our kids.

— [[id:806a7fda-b943-4160-8af1-e71c19d6f9a7][§David Perell]]
#+end_quote



