#+setupfile: ../hugo_setup.org
#+title: Precautionary Principle

The precautionary principle is the point of view that a course of action should not be taken when it's potential repercussions are not yet fully understood.

For example, some would say that we shouldn't accept a new vaccine because there could be unknown side-effects or that we shouldn't pursue [[file:nuclear_energy.org][§Nuclear Energy]] because of the potential for disaster.

While it is always important to be cautious with new technology, this way of thinking often hinders progress towards technologies that have the potential to greatly help humanity. People will dismiss innovation because of it's harm while ignoring it's potential for good. ([[file:digital_privacy.org][§Digital Privacy]])

- The risks of /not/ taking action are often ignored. For example, it is estimated to that shutting down all [[file:nuclear_energy.org][§Nuclear Power Plants]] in Japan following the [[file:fukushima_nuclear_disaster.org][§Fukushima Nuclear Disaster]], more people died because they could no longer afford to heat their homes in winter than did from the disaster itself.

- A major problem with bureaucracies, especially governments, is that they care tremendously when their actions bring harm, but tend to ignore the much greater devastation that often comes with inaction.

  - For example, this month (March 2021), many countries have blocked the use of the AstraZeneca Covid-19 vaccine because of an extremely minor risk of blood clots, despite the jab's excellent ability to prevent the disease.
