#+title: Productivity

- Be careful not to spend too much time organizing. According to [[https://pca.st/xuvhy4qq#t=748][Neil Pasricha]], we now spend 31% of our days bookmarking, prioritizing, and switching between tasks.

#+BEGIN_QUOTE
“Time lost trying to optimize your workflow is time lost, period.”

— Reddit user
#+END_QUOTE
  
- It's not a work-life balance, it's a flywheel. The more energy you can pour into one side of your life, the more energy you'll have for the rest. ([[https://pca.st/xuvhy4qq#t=5080][link]])
  
- Find small ponds. In our vast world, you'll never be as good as other people if you're in an ocean. Find something specific, do it well, and you will be rewarded.
  
- According to [[https://dcgross.com/improvising-for-productivity/?utm_campaign=Sunday%2520Snippets&utm_medium=email&utm_source=Revue%2520newsletter][Daniel Gross]], the more time we spend thinking about a task, the less likely we are to do it.
  - He states that it becomes less /novel/ — we have removed all the interesting aspects of it and all that is left is work.
  - This is why when you have a novel idea, it is easier to enter the [[file:flow_state.org][§Flow State]] than if you come back to it at a later time—it then feels like work.
    
- It is imperative that we understand why the task at hand is important for our goals. Without this understanding, we will always follow the path of least resistance: lethargy.

#+BEGIN_QUOTE
“Life's not all about productivity, but productivity is about managing time and time makes up life.”

— Ali Abdaal
#+END_QUOTE

#+BEGIN_QUOTE
“Civilization advances by extending the number of important operations which we can perform without thinking about them.”

— Alfred North Whitehead
#+END_QUOTE

#+BEGIN_QUOTE
“I'll never start a project that isn't already 80% finished.”

— [[file:tiago_forte.org][§Tiago Forte]]
#+END_QUOTE




