:PROPERTIES:
:ID:       a0220f3c-bd51-40fb-ad6b-714c63136d59
:ROAM_ALIASES: "\"Simple\""
:END:
#+setupfile: ../hugo_setup.org
#+setupfile:./hugo_setup.org

#+title: Simplicity

#+BEGIN_QUOTE
“Simplicity is the end result of long, hard work; not the starting point.”

— Frederick Maitland
#+END_QUOTE

#+BEGIN_QUOTE
“Mastering the mundane tasks of everyday life seems to be a gateway to living an extraordinary life.”
— [[id:daaf7a0e-7b41-4929-a39e-4ea2c6a25fa6][Tiago Forte]]
#+END_QUOTE

#+begin_quote
Simple, clear purpose and principles give rise to complex and intelligent behavior. Complex rules and regulations give rise to simple and stupid behavior.
— Dee Hock
#+end_quote



#+begin_quote
Good systems don't add options and features; they strip away complexity and distractions from the main work, which is thinking.
—  [[id:daaf7a0e-7b41-4929-a39e-4ea2c6a25fa6][Tiago Forte]] (summary of [[id:a0b85e10-52ee-4f4f-b8b5-960875348749][How to Take Smart Notes]])
#+end_quote

- Simple does not mean easy. Take simple ideas seriously. [[id:a0b85e10-52ee-4f4f-b8b5-960875348749][How to Take Smart Notes]]
  
- There are three stages of learning. In the first stage, our knowledge is superficial and uncomplicated. As we learn more about the intricacies of the subject, however, we learn how messy and complicated it really is. Only when we have reached mastery does everything seem simple again, because it has become a part of our thinking. [[id:698a8d51-5a32-4e47-91b1-ee8984c860ab][Learning]]
