:PROPERTIES:
:ID:       e7ab89d0-2ee7-4476-9948-bc0eb52cbf6c
:END:
#+setupfile: ../hugo_setup.org
#+title: Spherical Cow

- tags :: [[id:83a06686-dab0-46f9-98ab-1c10e4afacb8][§Physics]]

  Copied from wikipedia:

#+BEGIN_QUOTE
 Milk production at a dairy farm was low, so the farmer wrote to the local university, asking for help from academia. A multidisciplinary team of professors was assembled, headed by a theoretical physicist, and two weeks of intensive on-site investigation took place. The scholars then returned to the university, notebooks crammed with data, where the task of writing the report was left to the team leader. Shortly thereafter the physicist returned to the farm, saying to the farmer, "I have the solution, but it works only in the case of spherical cows in a vacuum". 
#+END_QUOTE


  
- The spherical cow is a metaphor for the ability to distill physical principles to their most basic and learn about the universe through these simplifications.

  - For example, the [[id:d663f204-bf8c-4c9f-9c24-d1f0b24d3b30][§Conservation of Momentum]] is rarely observed in real life because of friction. However, by stripping away the complexities of real life, we are able to learn about the nature of the universe.

- When the complexities are then re-added to the fundamental laws, patterns in nature can be predicted.

- This is unique to physics because physics is simple. In other fields such as biology and economics, the complexities define the subject and cannot be separated from fundamental principles.
