:PROPERTIES:
:ID:       c394a023-5630-4ae5-8d47-64aae6a83fb7
:END:
#+setupfile: ../hugo_setup.org
#+title: Surely You're Joking Mr Feynman
#+filetags: books

- author :: [[id:4bdd184b-5fe2-4f5b-bc49-e085d3269e52][Richard Feynman]]
* The Book in 3 Sentences
Richard Feynman was a famous twentieth-century scientist who—among other accomplishments—won the Nobel Prize in physics for his work in quantum electrodynamics. More than just a genius, Feynman was equally a prankster and an altogether whimsical character. This book is a transcript of many of his stories.

* Impressions
A hilarious book that completely dismisses the notion that all scientists are pompous British people. More than a comedy, Feynman's way of seeing the world is unique, and many of the lessons he shares throughout the book are powerful. Everyone, especially aspiring scientists, should read this book and learn from one of the most intelligent men of the 20th century.

* How the Book Changed Me
Feynman taught me that it's perfectly fine to not take science as seriously as others and to play with the most mundane of ideas. Like all of us, he once found himself burnt-out from his work and seemingly unable to continue. However, instead of throwing in the towel, he resolved to simply play with whatever physics intrigued him, which at that moment happened to be the motion of a spinning plate. The study of that plate eventually led to his Nobel prize.

* Top 3 Highlights
#+begin_quote
I had a scheme, which I still use today when somebody is explaining something that I’m trying to understand: I keep making up examples.

I can’t understand anything in general unless I’m carrying along in my mind a specific example and watching it go.

— [[id:4bdd184b-5fe2-4f5b-bc49-e085d3269e52][Richard Feynman]]
#+end_quote


#+begin_quote
So I got this new attitude. Now that I am burned out and I’ll never accomplish anything, I’ve got this nice position at the university teaching classes which I rather enjoy, and just like I read the Arabian Nights for pleasure, I’m going to play with physics, whenever I want to, without worrying about any importance whatsoever.
— 
#+end_quote




#+begin_quote
I was always dumb in that way. I never knew who I was talking to. I was always worried about the physics. If the idea looked lousy, I said it looked lousy. If it looked good, I said it looked good. Simple proposition.
#+end_quote


- imple proposition.
* Highlights

- I don’t know what’s the matter with people: they don’t learn by understanding; they learn by some other way—by rote, or something. Their knowledge is so fragile!

- I suddenly realized why Princeton was getting results. They were working with the instrument. They built the instrument; they knew where everything was, they knew how everything worked, there was no engineer involved,

- I raised my hand and shot out of my seat, screaming as loud as I could, to make sure that he would hear me: “MEEEEEEEEEEE!” He heard me all right, because there wasn’t another soul. My voice reverberated throughout the hall—it was very embarrassing. Eisenhart’s immediate reaction was, “Yes, of course, I knew you would volunteer, Mr. Feynman, but I was wondering if there would be anybody else.”

- Pauli was a very famous physicist—and by this time, I’m turning yellow. Finally, Wigner said, “Professor Einstein only rarely comes to our weekly seminars, but your work is so interesting that I’ve invited him specially, so he’s coming, too.”

- I had a scheme, which I still use today when somebody is explaining something that I’m trying to understand: I keep making up examples.

- (I’ve noticed that my dog can correctly tell which way I’ve gone in the house, especially if I’m barefoot, by smelling my footprints. So I tried to do that: I crawled around the rug on my hands and knees, sniffing, to see if I could tell the difference between where I walked and where I didn’t, and I found it impossible. So the dog is much better than I am.)

- I was always dumb in that way. I never knew who I was talking to. I was always worried about the physics. If the idea looked lousy, I said it looked lousy. If it looked good, I said it looked good. Simple proposition.

- In any thinking process there are moments when everything is going good and you’ve got wonderful ideas. Teaching is an interruption, and so it’s the greatest pain in the neck in the world. And then there are the longer periods of time when not much is coming to you. You’re not getting any ideas, and if you’re doing nothing at all, it drives you nuts! You can’t even say “I’m teaching my class.”

- Then I had another thought: Physics disgusts me a little bit now, but I used to enjoy doing physics. Why did I enjoy it? I used to play with it. I used to do whatever I felt like doing—it didn’t have to do with whether it was important for the development of nuclear physics, but whether it was interesting and amusing for me to play with.

- So I got this new attitude. Now that I am burned out and I’ll never accomplish anything, I’ve got this nice position at the university teaching classes which I rather enjoy, and just like I read the Arabian Nights for pleasure, I’m going to play with physics, whenever I want to, without worrying about any importance whatsoever.

- The diagrams and the whole business that I got the Nobel Prize for came from that piddling around with the wobbling plate.

- “Therefore,” he continued, “under no circumstances be a gentleman! You must disrespect the girls. Furthermore, the very first rule is, don’t buy a girl anything— not even a package of cigarettes—until you’ve asked her if she’ll sleep with you, and you’re convinced that she will, and that she’s not lying.”

- So when it was time to register for the class, we were standing outside, ready to go into the classroom, when this pneumatic blonde came along. You know how once in a while you get this feeling, WOW? She looked terrific. I said to myself, “Maybe she’s going to be in the Spanish class—that’ll be great!” But no, she walked into the Portuguese class. So I figured, What the hell—I might as well learn Portuguese.

- We realized that in America if the maid was delivering breakfast and the guy’s standing there, stark naked, there would be little screams and a big fuss. But in Japan they were completely used to it, and we felt that they were much more advanced and civilized about those things than we were.

- I can’t understand anything in general unless I’m carrying along in my mind a specific example and watching it go.

- “Well, yes, but it’s a different word—it’s more polite.” I gave up. I decided that wasn’t the language for me, and stopped learning Japanese.

- the physics teacher has the problem of always teaching techniques, rather than the spirit, of how to go about solving physical problems.

- And the reason that nobody got anywhere in that conference was that they hadn’t clearly defined the subject of “the ethics of equality in education,” and therefore no one knew exactly what they were supposed to talk about.

- But every time you get up to ask a question or to say something, I understand exactly what you mean—what the question is, and what you’re saying—so I thought you can’t be a professor!”

- I know that’s the way the government works; well, screw the government!

- The Greeks thought the seat of thinking was in the liver, for instance.

- But this long history of learning how to not fool ourselves—of having utter scientific integrity—is, I’m sorry to say, something that we haven’t specifically included in any particular course that I know of. We just hope you’ve caught on by osmosis.

- The first principle is that you must not fool yourself—and you are the easiest person to fool.
  
