:PROPERTIES:
:ID:       ef6e2566-99b7-4cdc-89e7-a392d7d8f2aa
:END:
#+setupfile: ../hugo_setup.org
#+title: The Importance of Arts Education

- tags :: [[id:03a97f88-f4d2-4d38-997c-b63f733692ae][University]]
  
- Science breeds narrow minds that over-rely on facts. Facts can be manipulated to support any agenda; it is the analysis and synthesis of facts with ideas that creates true understanding.

- Universities teach specialized skills for specialized students pursuing specialized careers. This is evident, so in their first week of school freshmen are inundated with speeches about the importance of 'thinking big' yet spend the next four years learning to ask the little questions. (see [[id:8c7dad95-3946-4dfd-a3ca-ba015d3a47ef][Educational Reform]])

  #+begin_quote
  When elite universities boast that they teach their students how to think, they mean that they teach them the analytic and rhetorical skills necessary for success in law or medicine or science or business. But a humanistic education is supposed to mean something more than that, as universities still dimly feel. So when students get to college, they hear a couple of speeches telling them to ask the big questions, and when they graduate, they hear a couple more speeches telling them to ask the big questions. And in between, they spend four years taking courses that train them to ask the little questions—specialized courses, taught by specialized professors, aimed at specialized students.
  — William Deresiewicz 
  #+end_quote
