#+setupfile: ../hugo_setup.org
#+title: The importance of privacy

*Privacy is about preventing those in power from gaining more control.* It is the right for you to choose what information you share, with whom you share it, and for your personal information not be used against you. Privacy is inalienable from freedom—without it you lose your autonomy.

- Companies should be required by law to collect only the data that is strictly required to provide you with their services.
  - Any other data is /never/ used to benefit you.

* Lack of regulation allows warrantless investigation of citizens

In 2020 it was revealed that the Department of Homeland Security had purchased a commercial database of location data which tracks the movement of millions of American cellphones ([[https://www.wsj.com/articles/federal-agencies-use-cellphone-location-data-for-immigration-enforcement-11581078600][source]]). This data was used to arrest immigrants suspected of crossing the border illegally.

* Privacy should be inalienable

Some argue that we should be able to see our personal data to companies. While this is better than our current system, it is a bad idea for two reasons:
1. You don't know what you're consenting to. If you sell your health data to medical researchers, that data might be used to deny you insurance.
2. Privacy is a collective concern. If you expose your genetic data, you're also exposing the genetic data of your family, who may not have consented. If you expose your location data, you're also exposing the location of your coworkers, because that data is also used to identify those you work with.
