#+setupfile: ../../hugo_setup.org
#+title: Deep Work: Rules for Focused Success in a Distracted World

- author :: [[file:../cal_newport.org][§Cal Newport]]
- tags :: [[file:../deep_work.org][§Deep Work]]

#+BEGIN_QUOTE
“Who you are, what you think, feel, and do, what you love—is the sum of what you focus on.”

— Cal Newport
#+END_QUOTE

The thesis of Cal Newport's book is very simple: deep, focused work without distraction is more valuable than shallow, distracted work. While this may seem self evident, it is the extent to which this meaningless work pervades our daily lives that Newport describes, along with strategies to maximize our [[file:../productivity.org][§Productivity]] through deep work.

*** *Part 1: The Idea*

**** *Deep work is valuable*

Newport argues that there are 3 types of people that will reap a disproportionate amount of benefit from the modern age:

1. People who are good with intelligent machines i.e. AI
2. People who are the very best at what they do
3. People with lots of money.

While this book contains no strategies for making more money directly, it argues that one can join the first two categories with the following skill set:

1. The ability to quickly master hard things.
2. The ability to produce elite level work quickly and efficiently.

The author continues by arguing that these two abilities are deeply intertwined with the ability to work deeply—an ability which has become both increasingly valuable and increasingly rare in today's society.

**** *Deep work is rare*

Our lives nowadays are constantly filled with distractions. E-mail, [[file:../social_media.org][§Social Media]], instant messaging etc. occupy a great deal of our time without providing much benefit in return. Employers expect us answer messages within minutes without understanding the following key point: *every time we switch from one context to another, we sacrifice concentration. Society nowadays equates busyness with productivity, which is almost completely orthogonal from the truth.* If you can learn to work deeply, you can outperform almost everyone.

**** *Deep work is meaningful*

#+BEGIN_QUOTE
“Like fingers pointing to the moon, other diverse disciplines from anthropology to education, behavioral economics to family counseling, similarly suggest that the skillful management of attention is the sine qua non of the good life and the key to improving virtually every aspect of your experience.”

— Winifred Gallagher
#+END_QUOTE

Humans are neurologically wired to seek challenges. That is why we almost always feel better after a hard day filled with challenges than after a day of rest. We take pride in our abilities, and to produce great work is deeply satisfying.

*** *Part 2: The Rules*

**** *Work deeply*

Without applying discipline and methodology to our work habits, we will almost always abandon deep work in favour of distractions. The first step to adopting deep work is to decide on one of the following scheduling philosophies:

1. Monastic philosophy: removing as much distraction from one's work at all times. No email, no shallow obligations, just work.
2. Bimodal philosophy: purposefully dividing one's time between deep and shallow work. For example, deep work might be delegated to 4 days per week or one season per year.
3. Rhythmic philosophy: making deep work a daily habit. For example, the hours 5–7 am are reserved for thesis writing.
4. Journalistic philosophy (me): scheduling deep work on a week-by-week or day-by-day basis. For people who don't have regular schedules.

Furthermore, *ritualize*. Decide when, how long, exactly what you'll do, and how you'll support your deep work sessions. For example, working in an isolated corner of the library for one hour with no internet and a healthy salad. By ritualizing your deep work sessions, your brain will be primed to slip into a state of deep concentration.

Sometimes, the scale of our work can feel so enormous that it feels almost impossible to start. Sometimes, we need to make *grand gestures* i.e. huge commitments that force us to start working. For example, J. K. Rowling checked herself into an expensive hotel until she finished to manuscript of /The Deathly Hallows/. For another example, William Shockley, one of the inventors of the transistor, locked himself in a hotel room until he had ironed out the details for a better design. He later won the Nobel Prize. By making a huge time, financial, or other commitment to a project, we can get seemingly impossible amounts of work done.

*Don't work alone.* Working with others can push you further than you could by yourself. However, this collaboration must be interspersed with periods of individual concentration.

It is often easy to identify a strategy required to achieve a goal, but the execution is challenging. Therefore, *execute like a business*.

1. Focus on a small number of wildly important goals.
2. Focus on the variables that you can control directly instead of the desired outcome.
3. Keep a scoreboard. Constructive competition is good.
4. Make yourself accountable for your work. Face your weaknesses.

*Take regular breaks and don't replace leisure with distractions.*

**** *Embrace boredom*

We tend to fill all of our free time with distractions, interspersed with bouts of focus. Instead, *take breaks from focus, not from distraction.* Consider scheduling the only time when internet is allowed.

Be more like Teddy Roosevelt and study with a feverish intensity:

#+BEGIN_QUOTE
“The amount of time he spent at his desk was comparatively small, but his concentration was so intense, and his reading so rapid, that he could afford more time off [from schoolwork] than most.”

— Edmund Morris (biographer)
#+END_QUOTE

To increase the intensity at which you work, *estimate how long a given task should take and then set yourself a hard limit which drastically reduces this time.* Furthermore, meditate productively. *During a walk or another period not occupied with work, focus your attention on a well-defined problem. If your attention wanders, practice bringing it back to the problem.*

Finally, Newport suggests learning how to memorize a deck of cards using the memory palace technique.

**** *Quit social media*

Evaluate the importance of each [[file:../social_media.org][§Social Media]] tool on your life. *Only use it if it brings significant value to your work or happiness.*

/*The Craftsman Approach to Tool Selection*: Identify the core factors that determine success and happiness in your professional and personal life. Adopt a tool only if its positive impacts on these factors substantially outweigh its negative impacts./ 

Identify the main high-level goals in your life. Ex:
1. Achieve a high level of academic performance throughout university.
2. Have meaningful connections and experiences with friends.

Does social media contribute to these goals?

Remember the *Law of the Vital Few:* the top 20% of activities in your life have 80% of the impact.

Consider quitting social media for a month and then evaluating whether or not you were missed on each platform.

Most importantly, *don't use the internet to entertain yourself!* Give your brain more real challenges throughout the day and you will feel more rested.

**** *Drain the shallows*

This chapter contains several tips which can reduced to the following statement repeated throughout the book: *shallow work is often much less important than it feels in the moment.* By minimizing the amount of time you spend on shallow and ultimately unproductive tasks, the more you will accomplish.

One notable piece of advice in this chapter is to finish all your work by five-thirty (or another chosen time). By limiting the amount of time you have to get work done during the day, you will not only work more efficiently, you will give your mind more time to rest during the evenings.
