:PROPERTIES:
:ID:       9967230e-a5fe-40de-83ed-18614c05c669
:END:
#+setupfile: ../../hugo_setup.org
#+title: Privacy is Power

* Highlights

- The internet is primarily funded by the collection, analysis, and trade of data – the data economy.

- If you are reading these words on a Kindle, or Google Books, or a Nook, they are measuring how long it takes for you to read each word, where you stop to take a break, and what you highlight.

- Privacy is about being able to keep certain intimate things to yourself – your thoughts, your experiences, your conversations, your plans.

- Human beings need privacy to be able to unwind from the burden of being with other people.

- *Privacy protects us from unwanted pressures and abuses of power. We need it to be autonomous individuals, and for democracies to function well we need citizens to be autonomous.*

- *If we give our data to companies, the wealthy will rule. If we give our data to governments, we will end up with some form of authoritarianism.*
  
- Privacy matters because it gives power to the people.

- your Samsung TV included the following warning: ‘Please be aware that if your spoken words include personal or other sensitive information, that information will be among the data captured and transmitted to a third party’.

- Bradley Malin and Latanya Sweeney used publicly available healthcare data and knowledge about particular diseases to re-identify 98 to 100 per cent of individuals on an ‘anonymized’ DNA database.

- *Everything you do while on Facebook gets tracked, from your mouse movements to the things you write and decide to delete before posting (your self-censorship).*
  - Source: https://web.archive.org/web/20201028210659/https://research.fb.com/wp-content/uploads/2016/11/self-censorship-on-facebook.pdf

- Facebook allowed Microsoft’s Bing search engine to see Facebook users’ friends without their consent, and it gave Netflix and Spotify the ability to read and even delete Facebook users’ ‘private’ messages.

- Mobile devices send unique identification codes (called media access control – or MAC – addresses) when they search for networks to go online. Shops use that information to study your behaviour.

- Our search engines know more about us than our spouses: we never lie to them or conceal our worries from them.

- In 2017, criminals got access to medical records from a clinic and blackmailed patients; they ended up publishing thousands of private photos, including nude ones, and personal data including passport scans and national insurance numbers.

- In the United States, obtaining real-time updates on any mobile phone’s location costs around $12.95.

- *At least when the police arrest you they allow you to remain silent, and warn you that anything you say may be used against you. As a subject of tech, you have no right to remain silent – trackers collect your data regardless of your not wanting them to – and you are not reminded that your data can and will be used against you.*

- At least three elements played a part in the erosion of our privacy: the discovery that personal data resulting from our digital lives could be very profitable, the terrorist attacks of 11 September 2001, and the mistaken belief that privacy was an outdated value.

- *people at Google had not looked favourably on advertising. Or so they claimed. Brin and Page wrote a paper in 1998 in which they expressed their concerns about depending on ads. ‘We expect that advertising funded search engines will be inherently biased towards the advertisers and away from the needs of the consumers,’ they wrote.*

- more than 80 per cent of Alphabet’s returns are from Google ads.

- Chrome, Maps, Pixel, Nest, and many others were designed as ways to collect even more data from you.

- ‘Larry [Page] opposed any path that would reveal our technological secrets or stir the privacy pot and endanger our ability to gather data. People didn’t know how much data we collected, but we were not doing anything evil with it, so why begin a conversation that would just confuse and concern everyone?’

- XKEYSCORE was a kind of search engine that allowed analysts to type in anyone’s address, telephone number, or IP address and then go through their recent online activity. Everyone’s communications were in there. Analysts could also watch people live as they went online and typed, letter by letter.

- Terrorism is a rare event; it is a needle in a haystack. Throwing more hay at the haystack doesn’t make finding the needle any easier – it makes it harder.

- the Trump administration has bought access to a commercial database that maps the movements of millions of mobile phones in the United States. Given that such data is for sale from data brokers, the government doesn’t need a warrant to get it.

- Terrible things like terrorist attacks and epidemics happen in the world – and they will continue to happen. To think we can prevent them if we give up our freedom and privacy is to believe in fairy tales.

- *Imagine having a master key for your life. A key or password that grants you access to the front door of your home, your bedroom, your diary, your computer, your phone, your car, your safe deposit, your health records. Would you go around making copies of that key and giving them out to strangers? Probably not. So why are you willing to give up your personal data to pretty much anyone who asks for it?*

- Part of what it means to be close to someone is sharing what makes you vulnerable, giving them the power to hurt you, and trusting that person never to take advantage of the privileged position granted by intimacy.

- *You might think your privacy is safe because you are a nobody – nothing special, interesting or important to see here. Don’t short-change yourself. If you weren’t that important, businesses and governments wouldn’t be going to so much trouble to spy on you. You have the power to lend your attention, your presence of mind.*

- *In liberal democracies (at their best), you’re not penalized in all spheres of life for small infractions committed in one area of life. For instance, playing loud music at home might make your neighbours hate you, and it might even earn you a visit from the police asking you to keep it down, but it will have no effect on your work life, or your financial credit score (unless your neighbour is your boss or your banker). In China, playing loud music, jaywalking, or cheating in a video game will make you lose points in a score that is used to grant and limit opportunities in all spheres of life.*

- Most people don’t know this, but as a consumer you have a secret score that determines how long you wait when calling a business, whether you can return items at a store, and the quality of service you receive. There is no opting out of being scored as a consumer – it is something imposed on you.

- Kashmir Hill, a reporter, requested her file from Sift, an American company that scores consumers. Hill’s file consisted of 400 pages with years of Yelp delivery orders, messages she’d sent on Airbnb, details about her devices, and much more.

- *Privacy is not about hiding serious wrongdoing. It’s about protecting ourselves from the possible wrongdoings of others, like criminals wanting to steal our money. It’s about blinding power so that it cannot use knowledge about us to become even more powerful.*

- Tech wants you to think that the innovations it brings into the market are inevitable. That’s what progress looks like, and progress cannot be stopped.

- If postal workers read our letters in the way that Gmail and third-party app developers have scanned our emails, they would go to jail.

- Privately owned advertising and surveillance networks are called ‘communities’, citizens are ‘users’, addiction to screens is labelled ‘engagement’, our most sensitive information is considered ‘data exhaust’ or ‘digital breadcrumbs’, spyware is called ‘cookies’, documents that describe our lack of privacy are titled ‘privacy policies’, and what used to be considered wiretapping is now the bedrock of the internet economy.

- Think about how voting booths are designed to protect you from external pressures – if no one can see who you vote for, no one can force you to vote against your wishes.

- we should never allow a technology to run amok based on a best-case scenario.

- To be in a world in which data is constantly weaponized is to feel perpetually threatened and distrustful of others. Such fear breeds conformity and silence.

- *When surveillance is everywhere, it becomes safer to keep quiet, or to echo the opinions that others accept. But society progresses through listening to the arguments of those who are critical, those who rebel against the status quo.*

- Only a third of Americans under thirty-five say that it is vital to live in a democracy,

- Read and support good journalism.

- Personal data can jeopardize national security, it can be used to corrupt democracy, it can threaten liberal societies by promoting a culture of exposure and vigilantism, and it can endanger the safety of individuals.

- Christopher Wylie, the Cambridge Analytica whistleblower, believes Brexit would not have won in the referendum if the data firm had not interfered.

- As the philosopher Thomas Nagel points out, ‘Everyone is entitled to commit murder in the imagination once in a while.’

- *While we are busy endlessly bickering online, trolling each other, and tearing people to shreds for human weaknesses that we probably share, our democracies are falling apart.*

- Data collection can kill. The Dutch had the highest death rate of Jews in occupied Europe – 73 per cent.

- The origin of the dark sides of the data economy is in the development of personalized advertising

- *Real-time bidding (RTB) sends your personal data to interested advertisers, often without your permission. Suppose Amazon gets that data and recognizes you as a user who has visited their website before in search of shoes. They might be willing to pay more than others to lure you into buying shoes. And that’s how you get shown an Amazon shoe ad.*

- Preliminary research shows that advertising using cookies does increase revenues, but only by around 4 per cent

- In response to the GDPR, the New York Times blocked personalized ads yet did not see ad revenues drop; rather, they rose.8

- Ads used to be interesting enough that you could compile them in a one-hour TV show and people would want to watch them. Not any more.

- Online advertisers should offer us information, instead of taking information from us.

- *According to a report commissioned by the Association of National Advertisers and The Advertising Coalition, advertising comprised 19 per cent of the United States’ total economic output in 2014.*

- The American advertising market value is larger than the banking industry.

- *That we are allowing companies to profit from the knowledge that someone has a disease, or has lost their son in a car accident, or has been the victim of a rape, is revolting.*

- As computer scientist Nigel Shadbolt and economist Roger Hampson argue, the right combination is to have ‘open public data’ and ‘secure private data’.

- Researchers, for instance, were able to infer correctly whether a person smoked based on their Facebook ‘likes’ in 73 per cent of cases.35 Suppose a company uses such an inference as a filter for hiring employees. If they have enough applicants for a job, they may not be bothered by being wrong about 27 per cent of those applicants because, from their perspective, they are still better off than if they hadn’t tried to infer that information.

- According to the law in Delaware – where Facebook, Google, and Twitter are incorporated – directors have to ‘treat stockholder welfare as the only end, considering other interests only to the extent that doing so is rationally related to stockholder welfare’.39

- It’s only a matter of time before a massive cyberattack happens. We know this, just as we knew a pandemic would happen sooner or later.

- How easily we lose sight of the fact that it is people who create algorithms, and often technology does not only not correct our mistakes – it amplifies them.

- Society needs autonomous and engaged citizens able to question and transform the status quo.

- To grow up into people with strong hearts and minds, children need to explore the world, make mistakes, and learn from their experiences, knowing that their blunders will not be recorded, much less used against them.

- Yves-Alexandre de Montjoye and his team have estimated that trackers installed on the phones of 1 per cent of London’s population could allow an attacker to track the real-time location of over half the city.

- Privacy should not be the price we have to pay to access any of our other rights – education, healthcare, and security prime among them.

- But convenience is also dangerous. It leads us to have sedentary lifestyles, to eat junk food, to support companies that harm society, to have monotonous and unsatisfactory daily routines, to be uneducated and politically apathetic.

- Unless you are a techie who knows how to build privacy for your phone, it’s probably a good idea to stay clear of Androids.

- About 47 per cent of netizens are blocking ads.

- People are increasingly getting news from social media.

- Surveillance is not only about what you do, but about what you think and feel – it’s under-the-skin surveillance.

- Privacy is how we blind the system so that it treats us impartially and fairly.
