#+setupfile: ../../hugo_setup.org
#+title: The Slight Edge

- author :: Jeff Olson
- tags :: [[file:../consistency.org][§Consistency]]
  
  #+BEGIN_QUOTE
  “The world is rife with hesitation, the cornerstone of mediocrity.”

  — Jeff Olson, /The Slight Edge/
  #+END_QUOTE

This book's premise is extremely simple: the direction of your life is entirely determined by the small actions that you take every single day. The actions that are easy to do, but equally easy not to do. These /simple daily disciplines/ compound over time, and can be summarised by the following graph:


When I started this book, I didn't expect to finish. It was poorly written and repetitive, but over time I realized that it is probably the most important book I've ever read. Because the thesis is so simple, I will not write comprehensive, but will instead direct you to my highlights, which more accurately capture the essence of this important work.

* Highlights

- “The only person you are destined to become is the person you decide to be.”

- There is a natural progression to everything in life: plant, cultivate, harvest.

- Parkinson’s Law goes like this: “Work expands to fill the time available for its completion.”

- Everything you need to do to transform your life is easy to do. It’s easy to become healthy, fit and vibrant. It’s easy to become financially independent. It’s easy to have a happy family and a life rich with meaningful friendships. It’s just a matter of mastering the mundane—of repeating simple little disciplines that, done consistently over time, will add up to the very biggest accomplishments.

- Success is the progressive realization of a worthy ideal.

- Patience is not an issue for the water hyacinth. It simply goes about its business, calmly, quietly doubling, until it covers the pond. You can do the same.

- Today I see these friends and ache for them: many now have failing health, are languishing in poor financial conditions, and seem to have lost their hopes for the future. What they have a hard time seeing is that my good health isn’t an accident, and their poor health isn’t a stroke of bad luck. They don’t see that we all, beach bums and millionaires alike, have gotten to where we are today the exact same way: the slight edge. They are victims of the quantum leap myth.

- Life means your health. The healthier you are, the more life you experience. Better health not only lets you live out all the days of a longer life, it also lets you live more life in each and every one of those days. Poor health is like a cloudy, smoggy day: it cuts off the sunlight. Let your health get bad enough, and you lose your life altogether.

- “You set out to lay that first brick as perfectly as a brick can be laid. And you do that every single day … and soon you have a wall.”


- But if our moods go up and down and our actions are inconsistent, if we smile at people sometimes and walk past them stony-faced at others because we’re “having a bad day,” then our positive and negative impact may just cancel each other out, and the net effect may not add up to much.


- *But successful people do what unsuccessful people are not willing to do—even when it doesn’t look like it makes any difference.*

- “A man can fail many times, but he isn’t a failure until he begins to blame somebody else.”

- It seems most people live with one foot in the past, saying, “If only things had been different, I would be successful.” And the other foot in the future saying, “When this or that happens, I will be happy and successful.” And they completely ignore the present—which is the only place where life actually occurs.

- No, you weren’t actually walking yet, not like the practiced strider you would become.

- You don’t need to be born with exceptional abilities to enter into mastery, nor is it reserved for the super-talented. You don’t even need to have gotten an early start. The upward journey of success on the slight edge curve is available to anyone who is willing to get on the path and stay on it.

- The people on the other side are hanging with the masses, and their lives are often more comfortable during that long early stretch. But they become more uncomfortable later on. Suddenly they find they don’t have the finances, don’t have the health or the happiness, no longer have the relationships, and their lives become very uncomfortable. By contrast, those on the success curve end up ever more comfortable as their lives progress, because over the course of time they continue to have the finances, the health and happiness, the relationships, the successes.

- Do what the majority won’t dare to do. Risk being the one, not one of the nineteen. Will people criticize you? Of course. But have you ever seen a statue erected for a critic? We don’t build statues for the 95 percent. We build them for the 5 percent.

- He shared how it is in the last 20 percent of the time we invest in a discipline that all the rewards come

- *Here’s a statistic that may blow your mind: among high school graduates who do not go on to college, 58 percent—more than half—never read a book again.*

- The average American will go bowling 233 times in his or her life—and they all have something better to do.

- Life is doing. If you aren’t doing, you’re dying.

- Would you like me to give you the formula for success? It’s quite simple, really. Double your rate of failure.… You’re thinking of failure as the enemy of success. But it isn’t at all. You can be discouraged by failure—or you can learn from it. So go ahead and make mistakes. Make all you can. Because, remember that’s where you’ll find success. On the other side of failure.

- Your relationships, financial health, attitudes, level of success in your career, and everything else about your life will tend to be very close to the average level of each of these conditions in your five closest friends and associates.

- “Be not afraid of going slowly; be afraid only of standing still.” —Chinese proverb

- It can take a good amount of energy and initiative to get yourself started in a new activity—but it takes far, far less to keep yourself doing it once you’ve started.

- It’s easy to stay active. It’s also easy not to. And if you stop, it won’t kill you today—but that simple error in judgment, compounded over time, will destroy the getting of any goal you’re after. Mary Kay Ash put it simply: “Give yourself something to work toward—constantly.”

- Here’s a powerful exercise: Instead of writing down what you’re going to do (chances are you’ve been doing that your whole adult life anyway, and it doesn’t make you any better at doing them), write down at the end of the day what you did do that day. What actions did you take today that made you successful? Did you read ten pages of a good book? Did you eat healthy food and get some good exercise? Did you engage in positive associations? Did you do the things you need to do to be successful in your business? Did you tell somebody, “I appreciate you”?

- That’s because what you focus on, grows. Which is why people who put a lot of energy into focusing on what they don’t want, by talking about it, thinking about it, complaining about it, or fretting about it, usually get precisely that unwanted thing.

- The world is rife with hesitation, the cornerstone of mediocrity.


- Hope begins in the dark, the stubborn hope that if you just show up and try to do the right thing, the dawn will come. You wait and watch and work: you don’t give up.

- In baseball, my theory is to strive for consistency, not to worry about the numbers. If you dwell on statistics you get shortsighted; if you aim for consistency, the numbers will be there at the end.

- Of all the factors possibly influencing health, vitality, and longevity, Buettner and his team compiled a list of nine. These people (1) live an active life, (2) cultivate purpose and a reason to wake up every morning, (3) take time to de-stress (appreciation, prayer, etc.), (4) stop eating when they are 80 percent full, (5) eat a diet emphasizing vegetables, especially beans, (6) have moderate alcohol intake (especially dark red wine), (7) play an active role in a faith-based community, (8) place a strong emphasis on family, and (9) are part of like-minded social circles with similar habits.

- don’t think it matters how successful you are, the funk is still going to get you at times. It comes for everyone. It doesn’t discriminate.

- There is no way I can understand love if I haven’t felt the hurt of loneliness.

- Everything curves. So when bad things are happening to you, embrace the funk. That, too, is cultivating positive outlook. When something is hard or difficult and adversity is at your front door, embrace it, because it will make you stronger and your life richer. You can’t know happiness unless you feel sadness. If you embrace it as part of the process, it can be life-altering.

- As the great literary figure John Leonard once wrote: It takes a long time to grow an old friend.

- A burning desire backed by faith simply means deeply, passionately wanting to get somewhere and knowing—not hoping, not wishing, but knowing that you’re going to get there.

- It’s bedtime, end of a long, rough day, and you’re beat. You head for bed—and there’s your book, sitting there looking at you. You’ve made a commitment to read ten pages a day. But man, you are tired. Don’t even know if you can keep your eyes open. What to do? “You know,” you say to yourself, “if I skip the ten pages, just for tonight, it’s no big deal.” And you know what? You’re absolutely right. It’s not going to make a huge difference, one way or the other. It is no big deal. And in that moment, you find out who you really are. It’s in that moment’s decision, when nobody else is watching and no one will ever know, when your choice is so slight, so subtle, so insignificant … it’s at that moment that you find out whether or not you have slight edge integrity.

- Me, I like to keep things as simple as possible, because simple is usually far more effective.

- *For a goal to come true: You must make it specific, give it a deadline, and write it down. You must look at it every day. You must have a plan to start with.*

- Here is another application of Pareto’s Law: 80 percent of everything you do tends to get done in the last 20 percent of the time available.

- You have to start with a plan, but the plan you start with will not be the plan that gets you there.

- names. One of them happened to be a doctor named Shapiro. The next week, I called Dr. Shapiro; we had a pleasant conversation, but nothing happened. I called him again, and then kept calling him. After about a month and a half of following up with him, he joined me in my business.

- _Successful people do what unsuccessful people are not willing to do; they put the slight edge to work for them, rather than against them, every day. They refuse to let themselves be swayed by their feelings, moods, or attitudes; they rule their lives by their philosophies and do what it takes to get the job done, whether they feel like it or not._

- Successful people focus on having a positive outlook. They understand that the funk gets everyone, and when it comes for them they embrace it, knowing it is refining them and deepening their appreciation of the rhythm of life. They take baby steps out of the funk and step back into positivity.



