#+setupfile: ../hugo_setup.org
#+title: The Wright Brothers

- author :: David McCullough
- tags ::
  
* Summary in 3 sentences
After several years of experimentation, Wilbur and Orville Wright made the first heavier than air flight in 1903. Their aircraft, named the /Wright Flyer,/ defied what was previously thought possible and left the world awestruck. They soon became famous, but never faltered from the humble character and passion for engineering.
   
* Impressions
A delightful book that kept me engaged the entire time. The audiobook, narrated by the author himself, was brilliant and the story he told left me inspired. It's easy to be led astray by what society deems is normal and by the notion that you need certain qualifications to achieve big things. Wilbur and Orville exemplify the joy of learning and of creating that I wish to emulate. This is a book that I should come back to. 

* How the Book Changed Me
This book proved to me that it's fine to be different from others. When you follow a different path from others, you're bound to receive criticism and doubt. The Wright Brothers listened only to themselves, and as a result they accomplished what they set out to achieve.
