#+setupfile: ../hugo_setup.org
#+title: The Inner Game of Tennis

  - author :: Timothy Gallwey
  - tags ::

    The central premise of the /Inner Game of Tennis/ is that there are two selves. Self 1 is the thinking, judgmental self who consciously controls our actions. Self 2, in contrast. is our intuition.

    Self 2 is naturally capable and embodies our childlike ability to learn through natural feedback loops.

    When people struggle to perform under pressure, talk about "choking", or try as hard as possible to execute a task perfectly, they are letting their first self interfere with their natural abilities.

People often try to learn a skill by identifying flaws in their performance and then trying to intentionally correct for them.

*Nonjudgmental awareness:*

Imagine you're trying to become a better public speaker. Instead of looking for flaws in your ability ("I speak to quickly and stumble over my words"), simply notice, without judgment, the sensations associated with public speaking (e.g. "I feel my throat tightening and my heart racing"). Now, instead of trying to correct for this

* Highlights 

- The player of the inner game comes to value the art of relaxed concentration above all other skills; he discovers a true basis for self-confidence; and he learns that the secret to winning any game lies in not trying too hard.

- I was beginning to learn what all good pros and students of tennis must learn: that images are better than words, showing better than telling, too much instruction worse than none, and that trying often produces negative results.

- The kind of relationship that exists between Self 1 and Self 2 is the prime factor in determining one’s ability to translate his knowledge of technique into effective action.

- Self 1 does not trust Self 2, even though it embodies all the potential you have developed up to that moment and is far more competent to control the muscle system than Self 1.

- By thinking too much and trying too hard, Self 1 has produced tension and muscle conflict in the body. He is responsible for the error, but he heaps the blame on Self 2 and then, by condemning it further, undermines his own confidence in Self 2. As a result the stroke grows worse and frustration builds.

- IT IS THE CONSTANT “THINKING” activity of Self 1, the ego-mind, which causes interference with the natural capabilities of Self 2.

- Man is a thinking reed but his great works are done when he is not calculating and thinking.

- When we unlearn how to be judgmental, it is possible to achieve spontaneous, focused play.

- Other common judgmental generalizations are, “I’m having a bad day,” “I always miss the easy ones,” “I’m slow,” etc.

- The key that unlocked Jack’s new backhand—which was really there all the time just waiting to be let out—was that in the instant he stopped trying to change his backhand, he saw it as it was. At first, with the aid of the mirror, he directly experienced his backswing. Without thinking or analyzing, he increased his awareness of that part of his swing. When the mind is free of any thought or judgment, it is still and acts like a mirror. Then and only then can we know things as they are.

- Always looking for approval and wanting to avoid disapproval, this subtle ego-mind sees a compliment as a potential criticism. It reasons, “If the pro is pleased with one kind of performance, he will be displeased by the opposite. If he likes me for doing well, he will dislike me for not doing well.”

- THE FIRST INNER SKILL to be developed in the Inner Game is that of nonjudgmental awareness.

- What it doesn’t already know, this inner intelligence learns with childlike ease.

- It is Self 1’s mistrust of Self 2 which causes both the interference called “trying too hard” and that of too much self-instruction.

- Anatomy tells us that muscles are two-way mechanisms; that is, a given muscle is either relaxed or contracted. It can’t be partially contracted any more than a light switch can be partially off.

- To Self 2, a picture is worth a thousand words.

- Many students of tennis are too stroke-conscious and not attentive enough to results.

- It is often helpful for these players to shift their attention from means to ends.

- The changes that Sally made in her forehand lay in the fact that she gave Self 2 a clear visual image of the results she desired.

- it is important not to make any conscious effort to keep the racket flat.

- When you toss the ball up, focus your attention on its seams, then let the serve serve itself.

- If you have missed the can, don’t be surprised and don’t try to correct for your error. This is most important. Again focus

- One begins believing that he is not a good tennis player and then acts this role, never allowing himself anything but glimpses of his true capabilities.

- The instruction, used as a conceptual “should” or “should not,” puts a shadow of fear between Self 2’s intuitive knowing and the action.

- a valid instruction derived from experience can help me if it guides me to my own experiential discovery of any given stroke possibility.

- Primarily because he hasn’t learned how to interfere with his own natural, untaught learning process.

- Habits are statements about the past, and the past is gone.

- there is no need to fight old habits.

- Awareness of what is, without judgment, is relaxing, and is the best precondition for change.

- Trust the process,

- Though the player knows his goal, he is not emotionally involved in achieving it and is therefore able to watch the results calmly and experience the process.

- Relaxation happens only when allowed, not as a result of “trying” or “making.”

- Fighting the mind does not work. What works best is learning to focus it.

- To still the mind one must learn to put it somewhere. It cannot just be let go; it must be focused.

- The focused mind only picks up on those aspects of a situation that are needed to accomplish the task at hand.

- Natural focus occurs when the mind is interested.

- If your eyes are squinting or straining, you are trying too hard.

- The greatest lapses in concentration come when we allow our minds to project what is about to happen or to dwell on what has already happened.

- All who enter even a little into that state of being present will experience a calmness and a degree of ecstasy which they will want to repeat.

- Phil Jackson, coach of Michael Jordan and the four-time NBA Champions, the Chicago Bulls, describes the state of Self 2 focus very well in his book, Sacred Hoops: “Basketball is a complex dance that requires shifting from one objective to another at lightning speed. To excel, you need to act with a clear mind and be totally focused on what everyone on the floor is doing. The secret is not thinking. That doesn’t mean being stupid; it means quieting the endless jabbering of thoughts so that your body can do instinctively what it’s been trained to do without the mind getting in the way.

- We live in an achievement-oriented society where people tend to be measured by their competence in various endeavors.

- From this pattern, one basic message came across loud, clear and often: you are a good person and worthy of respect only if you do things successfully.

- the intelligent, beautiful and competent tend to regard themselves as better people.

- When love and respect depend on winning or doing well in a competitive society, it is inevitable (since every winner requires a loser and every top performance many inferior ones) that there will be many people who feel a lack of love and respect.

- The answer was quite unexpected. What I really wanted, I realized, was to overcome the nervousness that was preventing me from playing my best and enjoying myself. I wanted to overcome the inner obstacle that had plagued me for so much of my life. I wanted to win the inner game.

- It is as if some believe that only by being the best, only by being a winner, will they be eligible for the love and respect they seek.

- My theory was that I would be unconcerned with how well I was doing in relation to my opponent and absorbed solely in achieving excellence for its own sake.

- I don’t want to promote the idea of playing angry as the key to winning. If there was a key that day it was that I played sincerely.

- It is only against the big waves that he is required to use all his skill, all his courage and concentration to overcome; only then can he realize the true limits of his capacities.

- So I arrived at the startling conclusion that true competition is identical with true cooperation. Each player tries his hardest to defeat the other, but in this use of competition it isn’t the other person we are defeating; it is simply a matter of overcoming the obstacles he presents.

- Then, instead of learning focus to improve his tennis, he practices tennis to improve his focus.

- Perhaps the most indispensable tool for human beings in modern times is the ability to remain calm in the midst of rapid and unsettling changes.

- Self 2’s needs come with a gentle but constant urging. A certain feeling of contentment attends a person whenever he or she is acting in sync with this self.

- I don’t think anyone’s Self 2 needs improvement from birth to death. It has always been fine.

- “Abandon” is a good word to describe what happens to a tennis player who feels he has nothing to lose. He stops caring about the outcome and plays all out. It is a letting go of the concerns of Self 1 and letting in of the natural concerns of a deeper and truer self. It is caring, yet not caring; it is effort, but effortless at the same time.

- I honestly believe that during the past few hundred years, mankind has been so absorbed with overcoming external challenges that the essential need to focus on inner challenges has been neglected.

