:PROPERTIES:
:ID:       a2a4e2da-a09c-4bc6-96e2-1878ac19d8c7
:ROAM_REFS: cite:zhangConversationsGoneAwry2018
:END:
#+setupfile: .../hugo_setup.org
#+TITLE: Conversations Gone Awry: Detecting Early Signs of Conversational Failure



- keywords :: Text_Analysis,WRDS150
- author :: Zhang, J., Chang, J. P., Danescu-Niculescu-Mizil, Cristian, Dixon, L., Hua, Y., Thain, N., & Taraborelli, D.

* Notes
- This study attempted to be the first to computationally quantify the relationship between specific conversational strategies used in online discussions and the likelihood that the conversations will consequently maintain their civility.

- Using a machine learning, a model was trained to identify subtle markers of underlying tensions—not merely insults—that signal the demise of a conversation.
  
- The models were trained using a corpus of Wikipedia talk page discussions.
  - 50 million conversations across 16 million talk pages.

  - The dataset comprised of 1,270 distinct conversations with an average length of 4.6 comments each.

  - The dataset included only conversations that were initially identified as civil.

* Politeness Strategies

- An unsupervised neural network was trained to identify a set of linguistic markers of politeness outlined by cite:brown2009politeness. These include gratitude, greetings, and hedging.
- Markers of impoliteness were also considered, including direct questions and the usage of second person pronouns (e.g. "/Your/ opinion is invalid...").
